(eval-when-compile    (require 'color-theme))
(defun color-theme-dmb-dark3 ()
  "Color theme by David M. Boon, created 2013-07-13."
  (interactive)
  (color-theme-install
   '(color-theme-dmb-dark3
     ((background-color . "unspecified-bg")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (foreground-color . "#dadada")
      (mouse-color . "#323232"))
     ((ac-fuzzy-cursor-color . "red")
      (compilation-message-face . underline)
      (erc-button-face . erc-button)
      (erc-button-mouse-face . highlight)
      (erc-button-nickname-face . erc-nick-default-face)
      (erc-interpret-mirc-color . t)
      (hl-line-face . hl-line)
      (ibuffer-deletion-face . error)
      (ibuffer-filter-group-name-face . bold)
      (ibuffer-marked-face . warning)
      (ibuffer-title-face . font-lock-type-face)
      (ispell-highlight-face . flyspell-incorrect)
      (list-matching-lines-buffer-name-face . underline)
      (list-matching-lines-face . match)
      (org-goto-interface . outline)
      (widget-mouse-face . highlight))
     (default ((t (:stipple nil :background "unspecified-bg" :foreground "#dadada" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 1 :width normal :foundry "default" :family "default"))))
     (ac-candidate-face ((t (:background "lightgray" :foreground "black" :underline "darkgray"))))
     (ac-completion-face ((t (:foreground "darkgray" :underline t))))
     (ac-gtags-candidate-face ((t (:background "lightgray" :foreground "navy"))))
     (ac-gtags-selection-face ((t (:background "navy" :foreground "white"))))
     (ac-selection-face ((t (:background "steelblue" :foreground "white"))))
     (ac-yasnippet-candidate-face ((t (:background "sandybrown" :foreground "black"))))
     (ac-yasnippet-selection-face ((t (:background "coral3" :foreground "white"))))
     (bg:erc-color-face0 ((t (:background "White"))))
     (bg:erc-color-face1 ((t (:background "black"))))
     (bg:erc-color-face10 ((t (:background "lightblue1"))))
     (bg:erc-color-face11 ((t (:background "cyan"))))
     (bg:erc-color-face12 ((t (:background "blue"))))
     (bg:erc-color-face13 ((t (:background "deeppink"))))
     (bg:erc-color-face14 ((t (:background "gray50"))))
     (bg:erc-color-face15 ((t (:background "gray90"))))
     (bg:erc-color-face2 ((t (:background "blue4"))))
     (bg:erc-color-face3 ((t (:background "green4"))))
     (bg:erc-color-face4 ((t (:background "red"))))
     (bg:erc-color-face5 ((t (:background "brown"))))
     (bg:erc-color-face6 ((t (:background "purple"))))
     (bg:erc-color-face7 ((t (:background "orange"))))
     (bg:erc-color-face8 ((t (:background "yellow"))))
     (bg:erc-color-face9 ((t (:background "green"))))
     (bold ((t (:bold t :weight bold))))
     (bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (bookmark-menu-heading ((t (:foreground "PaleGreen"))))
     (border ((t (nil))))
     (buffer-menu-buffer ((t (:bold t :weight bold))))
     (buffer-menu-buffer-name ((t (:foreground "Blue"))))
     (buffer-menu-current-buffer ((t (:background "Aquamarine" :foreground "Red"))))
     (buffer-menu-delete-mark ((t (:background "Red" :foreground "Aquamarine"))))
     (buffer-menu-directory-buffer ((t (:background "LightBlue" :foreground "Blue"))))
     (buffer-menu-file-name ((t (:foreground "DarkMagenta"))))
     (buffer-menu-flagged-buffer ((t (:foreground "Red"))))
     (buffer-menu-headings ((t (:background "DarkGreen" :foreground "Orange"))))
     (buffer-menu-marked-buffer ((t (:underline t))))
     (buffer-menu-mode ((t (:foreground "DarkGreen"))))
     (buffer-menu-modified-mark ((t (:foreground "DarkOrange"))))
     (buffer-menu-read-only-mark ((t (:foreground "burlywood"))))
     (buffer-menu-save-mark ((t (:background "Blue" :foreground "Orange"))))
     (buffer-menu-size ((t (:foreground "DarkRed"))))
     (buffer-menu-star-buffer ((t (:foreground "DarkBlue"))))
     (buffer-menu-time ((t (:foreground "DarkGoldenrod4"))))
     (buffer-menu-view-mark ((t (:background "Aquamarine" :foreground "Red"))))
     (button ((t (:underline t :foreground "cyan1"))))
     (c-annotation-face ((t (:foreground "Aquamarine"))))
     (calendar-today ((t (:underline t))))
     (change-log-acknowledgment ((t (:foreground "gray53"))))
     (change-log-conditionals ((t (:foreground "LightGoldenrod"))))
     (change-log-date ((t (:foreground "LightSalmon"))))
     (change-log-email ((t (:foreground "LightGoldenrod"))))
     (change-log-file ((t (:foreground "LightSkyBlue"))))
     (change-log-function ((t (:foreground "LightGoldenrod"))))
     (change-log-list ((t (:foreground "Cyan1"))))
     (change-log-name ((t (:foreground "Aquamarine"))))
     (comint-highlight-input ((t (:bold t :weight bold))))
     (comint-highlight-prompt ((t (:foreground "cyan"))))
     (compilation-column-number ((t (:foreground "LightSalmon"))))
     (compilation-error ((t (:bold t :weight bold :foreground "Pink"))))
     (compilation-info ((t (:bold t :weight bold :foreground "Green1"))))
     (compilation-line-number ((t (:foreground "Cyan1"))))
     (compilation-mode-line-exit ((t (:bold t :foreground "ForestGreen" :weight bold))))
     (compilation-mode-line-fail ((t (:bold t :foreground "Red1" :weight bold))))
     (compilation-mode-line-run ((t (:bold t :foreground "DarkOrange" :weight bold))))
     (compilation-warning ((t (:bold t :weight bold :foreground "DarkOrange"))))
     (completions-annotations ((t (:italic t :slant italic))))
     (completions-common-part ((t (:family "default" :foundry "default" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#dadada" :background "unspecified-bg" :stipple nil :height 1))))
     (completions-first-difference ((t (:bold t :weight bold))))
     (css-property ((t (:foreground "LightGoldenrod"))))
     (css-proprietary-property ((t (:foreground "LightGoldenrod"))))
     (css-selector ((t (:foreground "LightSkyBlue"))))
     (cursor ((t (:background "#1E16ED"))))
     (custom-button ((t (nil))))
     (custom-button-mouse ((t (nil))))
     (custom-button-pressed ((t (nil))))
     (custom-button-pressed-unraised ((t (:bold t :weight bold :foreground "violet"))))
     (custom-button-unraised ((t (:bold t :weight bold))))
     (custom-changed ((t (:background "blue1" :foreground "white"))))
     (custom-comment ((t (:background "yellow3" :foreground "black"))))
     (custom-comment-tag ((t (:foreground "gray80"))))
     (custom-documentation ((t (nil))))
     (custom-face-tag ((t (:bold t :weight bold :foreground "light blue"))))
     (custom-group-subtitle ((t (:bold t :weight bold))))
     (custom-group-tag ((t (:bold t :family "Sans Serif" :foreground "light blue" :weight bold :height 1.2))))
     (custom-group-tag-1 ((t (:bold t :family "Sans Serif" :foreground "pink" :weight bold :height 1.2))))
     (custom-invalid ((t (:background "red1" :foreground "yellow1"))))
     (custom-link ((t (:underline t :foreground "cyan1"))))
     (custom-modified ((t (:background "blue1" :foreground "white"))))
     (custom-rogue ((t (:background "black" :foreground "pink"))))
     (custom-saved ((t (:underline t))))
     (custom-set ((t (:background "white" :foreground "blue1"))))
     (custom-state ((t (:foreground "lime green"))))
     (custom-themed ((t (:background "blue1" :foreground "white"))))
     (custom-variable-button ((t (:bold t :underline t :weight bold))))
     (custom-variable-tag ((t (:bold t :foreground "light blue" :weight bold))))
     (custom-visibility ((t (:underline t :foreground "cyan1" :height 0.8))))
     (diary ((t (:foreground "yellow1"))))
     (diff-added ((t (:background "#335533" :foreground "#00cc33"))))
     (diff-changed ((t (nil))))
     (diff-context ((t (:foreground "#666666"))))
     (diff-file-header ((t (:bold t :background "grey60" :weight bold))))
     (diff-function ((t (:background "grey45"))))
     (diff-header ((t (:background "grey45"))))
     (diff-hunk-header ((t (:background "grey45"))))
     (diff-index ((t (:bold t :weight bold :background "grey60"))))
     (diff-indicator-added ((t (:foreground "#00cc33" :background "#335533"))))
     (diff-indicator-changed ((t (nil))))
     (diff-indicator-removed ((t (:foreground "#ff0000" :background "#553333"))))
     (diff-nonexistent ((t (:bold t :weight bold :background "grey60"))))
     (diff-refine-added ((t (:background "#22aa22"))))
     (diff-refine-change ((t (:background "#aaaa22"))))
     (diff-refine-removed ((t (:background "#aa2222"))))
     (diff-removed ((t (:background "#553333" :foreground "#ff0000"))))
     (dired-directory ((t (:foreground "LightSkyBlue"))))
     (dired-flagged ((t (:bold t :weight bold :foreground "Pink"))))
     (dired-header ((t (:foreground "PaleGreen"))))
     (dired-ignored ((t (:foreground "grey70"))))
     (dired-mark ((t (:foreground "Aquamarine"))))
     (dired-marked ((t (:bold t :weight bold :foreground "DarkOrange"))))
     (dired-perm-write ((t (:foreground "gray53"))))
     (dired-symlink ((t (:foreground "Cyan1"))))
     (dired-warning ((t (:bold t :foreground "Pink" :weight bold))))
     (dmb-face-five ((t (:foreground "IndianRed"))))
     (dmb-face-four ((t (:foreground "#997009"))))
     (dmb-face-hi-light-line-error ((t (:foreground "maroon"))))
     (dmb-face-ibuffer-elisp ((t (:foreground "SeaGreen"))))
     (dmb-face-ibuffer-grep ((t (:foreground "yellow4"))))
     (dmb-face-ibuffer-jde ((t (:foreground "MediumAquamarine"))))
     (dmb-face-ibuffer-sql ((t (:foreground "grey50"))))
     (dmb-face-ibuffer-sql-interactive ((t (:foreground "DarkOrange"))))
     (dmb-face-light-blue ((t (:foreground "LightSkyBlue"))))
     (dmb-face-one ((t (:foreground "midnight blue"))))
     (dmb-face-onex ((t (:foreground "LightSkyBlue"))))
     (dmb-face-six ((t (:foreground "DarkSlateBlue"))))
     (dmb-face-three ((t (:foreground "DarkOrange"))))
     (dmb-face-two ((t (:foreground "medium sea green"))))
     (dmb-grep-hit-face ((t (:foreground "DarkSlateBlue" :underline nil))))
     (dmb-grep-match-face ((t (:foreground "DarkSlateBlue" :underline nil))))
     (dmb-mark-face ((t (:foreground "cyan" :underline nil))))
     (dmb-mode-line-directory-face ((t (:foreground "#357797"))))
     (dmb-notes-txt-face ((t (:foreground "DodgerBlue" :underline nil))))
     (dropdown-list-face ((t (:family "default" :foundry "default" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :stipple nil :background "lightyellow" :foreground "black" :height 1))))
     (dropdown-list-selection-face ((t (:foreground "black" :stipple nil :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "default" :family "default" :background "purple" :height 1))))
     (epa-field-body ((t (:italic t :foreground "turquoise" :slant italic))))
     (epa-field-name ((t (:bold t :foreground "PaleTurquoise" :weight bold))))
     (epa-mark ((t (:bold t :foreground "orange" :weight bold))))
     (epa-string ((t (:foreground "lightyellow"))))
     (epa-validity-disabled ((t (:italic t :slant italic))))
     (epa-validity-high ((t (:bold t :foreground "PaleTurquoise" :weight bold))))
     (epa-validity-low ((t (:italic t :slant italic))))
     (epa-validity-medium ((t (:italic t :foreground "PaleTurquoise" :slant italic))))
     (erc-action-face ((t (:bold t :weight bold))))
     (erc-bold-face ((t (:bold t :weight bold))))
     (erc-button ((t (:bold t :weight bold))))
     (erc-command-indicator-face ((t (:bold t :weight bold))))
     (erc-current-nick-face ((t (:bold t :foreground "DarkTurquoise" :weight bold))))
     (erc-dangerous-host-face ((t (:foreground "red"))))
     (erc-default-face ((t (nil))))
     (erc-direct-msg-face ((t (:foreground "IndianRed"))))
     (erc-error-face ((t (:foreground "red"))))
     (erc-fool-face ((t (:foreground "dim gray"))))
     (erc-header-line ((t (:background "grey90" :foreground "grey20"))))
     (erc-input-face ((t (:foreground "brown"))))
     (erc-inverse-face ((t (:background "Black" :foreground "White"))))
     (erc-keyword-face ((t (:bold t :foreground "pale green" :weight bold))))
     (erc-my-nick-face ((t (:bold t :foreground "brown" :weight bold))))
     (erc-nick-default-face ((t (:bold t :weight bold))))
     (erc-nick-msg-face ((t (:bold t :foreground "IndianRed" :weight bold))))
     (erc-notice-face ((t (:bold t :foreground "SlateBlue" :weight bold))))
     (erc-pal-face ((t (:bold t :foreground "Magenta" :weight bold))))
     (erc-prompt-face ((t (:bold t :background "lightBlue2" :foreground "Black" :weight bold))))
     (erc-timestamp-face ((t (:bold t :foreground "green" :weight bold))))
     (erc-underline-face ((t (:underline t))))
     (error ((t (:bold t :foreground "Pink" :weight bold))))
     (escape-glyph ((t (:foreground "cyan"))))
     (ffap ((t (:background "darkolivegreen"))))
     (fg:erc-color-face0 ((t (:foreground "White"))))
     (fg:erc-color-face1 ((t (:foreground "black"))))
     (fg:erc-color-face10 ((t (:foreground "lightblue1"))))
     (fg:erc-color-face11 ((t (:foreground "cyan"))))
     (fg:erc-color-face12 ((t (:foreground "blue"))))
     (fg:erc-color-face13 ((t (:foreground "deeppink"))))
     (fg:erc-color-face14 ((t (:foreground "gray50"))))
     (fg:erc-color-face15 ((t (:foreground "gray90"))))
     (fg:erc-color-face2 ((t (:foreground "blue4"))))
     (fg:erc-color-face3 ((t (:foreground "green4"))))
     (fg:erc-color-face4 ((t (:foreground "red"))))
     (fg:erc-color-face5 ((t (:foreground "brown"))))
     (fg:erc-color-face6 ((t (:foreground "purple"))))
     (fg:erc-color-face7 ((t (:foreground "orange"))))
     (fg:erc-color-face8 ((t (:foreground "yellow"))))
     (fg:erc-color-face9 ((t (:foreground "green"))))
     (file-name-shadow ((t (:foreground "grey70"))))
     (fixed-pitch ((t (:family "Monospace"))))
     (flymake-errline ((t (:underline "OrangeRed"))))
     (flymake-warnline ((t (:underline "DarkSlateBlue"))))
     (flyspell-duplicate ((t (:bold t :weight bold :foreground "DarkOrange" :underline t))))
     (flyspell-incorrect ((t (:bold t :weight bold :foreground "Pink" :underline t))))
     (font-lock-builtin-face ((t (:foreground "LightSteelBlue"))))
     (font-lock-comment-delimiter-face ((t (:foreground "gray53"))))
     (font-lock-comment-face ((t (:foreground "white"))))
     (font-lock-constant-face ((t (:foreground "Aquamarine"))))
     (font-lock-doc-face ((t (:foreground "LightSalmon"))))
     (font-lock-doc-string-face ((t (nil))))
     (font-lock-function-name-face ((t (:foreground "LightSkyBlue"))))
     (font-lock-keyword-face ((t (:foreground "Cyan1"))))
     (font-lock-negation-char-face ((t (nil))))
     (font-lock-preprocessor-face ((t (:foreground "LightSteelBlue"))))
     (font-lock-regexp-grouping-backslash ((t (:bold t :weight bold))))
     (font-lock-regexp-grouping-construct ((t (:bold t :weight bold))))
     (font-lock-string-face ((t (:foreground "LightSalmon"))))
     (font-lock-type-face ((t (:foreground "PaleGreen"))))
     (font-lock-variable-name-face ((t (:foreground "LightGoldenrod"))))
     (font-lock-warning-face ((t (:bold t :weight bold :foreground "Pink"))))
     (fringe ((t (:background "grey10"))))
     (glyphless-char ((t (:bold t :weight bold))))
     (header-line ((t (:box (:line-width -1 :style released-button) :foreground "black" :background "grey75" :inverse-video nil :underline t))))
     (helm-action ((t (:underline t))))
     (helm-bookmark-directory ((t (:foreground "DarkRed" :background "LightGray"))))
     (helm-bookmark-file ((t (:foreground "Deepskyblue2"))))
     (helm-bookmark-gnus ((t (:foreground "magenta"))))
     (helm-bookmark-info ((t (:foreground "green"))))
     (helm-bookmark-man ((t (:foreground "Orange4"))))
     (helm-bookmark-w3m ((t (:foreground "yellow"))))
     (helm-bookmarks-su ((t (:foreground "red"))))
     (helm-buffer-not-saved ((t (:foreground "Indianred2"))))
     (helm-buffer-saved-out ((t (:background "black" :foreground "red"))))
     (helm-buffer-size ((t (:foreground "RosyBrown"))))
     (helm-candidate-number ((t (:background "Yellow" :foreground "black"))))
     (helm-ff-directory ((t (:background "LightGray" :foreground "DarkRed"))))
     (helm-ff-executable ((t (:foreground "green"))))
     (helm-ff-file ((t (:foreground "LightSteelBlue"))))
     (helm-ff-invalid-symlink ((t (:background "red" :foreground "black"))))
     (helm-ff-prefix ((t (:background "yellow" :foreground "black"))))
     (helm-ff-symlink ((t (:foreground "DarkOrange"))))
     (helm-grep-cmd-line ((t (:foreground "#00cc33" :background "#335533"))))
     (helm-grep-file ((t (:foreground "BlueViolet" :underline t))))
     (helm-grep-finish ((t (:foreground "Green"))))
     (helm-grep-lineno ((t (:foreground "Darkorange1"))))
     (helm-grep-match ((t (:background "RoyalBlue3"))))
     (helm-grep-running ((t (:foreground "Red"))))
     (helm-header ((t (:underline t :inverse-video nil :background "grey75" :foreground "black" :box (:line-width -1 :style released-button)))))
     (helm-match ((t (:background "RoyalBlue3"))))
     (helm-moccur-buffer ((t (:foreground "DarkTurquoise" :underline t))))
     (helm-selection ((t (:background "ForestGreen" :underline t))))
     (helm-selection-line ((t (:background "IndianRed4" :underline t))))
     (helm-separator ((t (:foreground "red"))))
     (helm-source-header ((t (:bold t :background "#22083397778B" :foreground "white" :weight bold :height 1.3 :family "Sans Serif"))))
     (helm-visible-mark ((t (:background "green1" :foreground "black"))))
     (help-argument-name ((t (:italic t :slant italic))))
     (highlight ((t (:background "darkolivegreen"))))
     (hl-line ((t (:background "darkolivegreen"))))
     (holiday ((t (:background "chocolate4"))))
     (ido-first-match ((t (:bold t :weight bold))))
     (ido-incomplete-regexp ((t (:bold t :foreground "Pink" :weight bold))))
     (ido-indicator ((t (:background "red1" :foreground "yellow1" :width condensed))))
     (ido-only-match ((t (:foreground "ForestGreen"))))
     (ido-subdir ((t (:foreground "red1"))))
     (ido-virtual ((t (:foreground "LightSteelBlue"))))
     (isearch ((t (:background "palevioletred2" :foreground "brown4"))))
     (isearch-fail ((t (:background "red4"))))
     (italic ((t (:italic t :slant italic))))
     (js2-error-face ((t (:foreground "red"))))
     (js2-external-variable-face ((t (:foreground "orange"))))
     (js2-function-param-face ((t (:foreground "SeaGreen"))))
     (js2-instance-member-face ((t (:foreground "DarkOrchid"))))
     (js2-jsdoc-html-tag-delimiter-face ((t (:foreground "green"))))
     (js2-jsdoc-html-tag-name-face ((t (:foreground "yellow"))))
     (js2-jsdoc-tag-face ((t (:foreground "SlateGray"))))
     (js2-jsdoc-type-face ((t (:foreground "SteelBlue"))))
     (js2-jsdoc-value-face ((t (:foreground "PeachPuff3"))))
     (js2-magic-paren-face ((t (:underline t))))
     (js2-private-function-call-face ((t (:foreground "goldenrod"))))
     (js2-private-member-face ((t (:foreground "PeachPuff3"))))
     (js2-warning-face ((t (:underline "orange"))))
     (lazy-highlight ((t (:background "paleturquoise4"))))
     (link ((t (:foreground "cyan1" :underline t))))
     (link-visited ((t (:underline t :foreground "violet"))))
     (log-edit-header ((t (:foreground "Cyan1"))))
     (log-edit-summary ((t (:foreground "LightSkyBlue"))))
     (log-edit-unknown-header ((t (:foreground "gray53"))))
     (magit-branch ((t (:box (:line-width -1 :style released-button) :foreground "black" :background "grey75" :inverse-video nil :underline t))))
     (magit-diff-add ((t (:foreground "#00cc33" :background "#335533"))))
     (magit-diff-del ((t (:foreground "#ff0000" :background "#553333"))))
     (magit-diff-file-header ((t (:bold t :weight bold :background "grey60"))))
     (magit-diff-hunk-header ((t (:background "grey45"))))
     (magit-diff-merge-current ((t (:foreground "LightSteelBlue"))))
     (magit-diff-merge-proposed ((t (:foreground "LightSteelBlue"))))
     (magit-diff-merge-separator ((t (:foreground "LightSteelBlue"))))
     (magit-diff-none ((t (:foreground "#666666"))))
     (magit-header ((t (:underline t :inverse-video nil :background "grey75" :foreground "black" :box (:line-width -1 :style released-button)))))
     (magit-item-highlight ((t (:background "deep sky blue"))))
     (magit-item-mark ((t (:background "SkyBlue4"))))
     (magit-log-author ((t (:foreground "tomato"))))
     (magit-log-date ((t (nil))))
     (magit-log-graph ((t (:foreground "grey80"))))
     (magit-log-head-label-bisect-bad ((t (:background "IndianRed1" :foreground "IndianRed4" :box 1))))
     (magit-log-head-label-bisect-good ((t (:background "light green" :foreground "dark olive green" :box 1))))
     (magit-log-head-label-default ((t (:background "Grey50" :box 1))))
     (magit-log-head-label-local ((t (:background "Grey13" :foreground "LightSkyBlue1" :box 1))))
     (magit-log-head-label-patches ((t (:background "IndianRed1" :foreground "IndianRed4" :box 1))))
     (magit-log-head-label-remote ((t (:background "Grey11" :foreground "DarkSeaGreen2" :box 1))))
     (magit-log-head-label-tags ((t (:background "LemonChiffon1" :foreground "goldenrod4" :box 1))))
     (magit-log-message ((t (nil))))
     (magit-log-sha1 ((t (:foreground "tomato"))))
     (magit-section-title ((t (:box (:line-width -1 :style released-button) :foreground "black" :background "grey75" :inverse-video nil :underline t))))
     (magit-whitespace-warning-face ((t (:background "red1"))))
     (match ((t (:background "RoyalBlue3"))))
     (menu ((t (nil))))
     (minibuffer-prompt ((t (:foreground "cyan"))))
     (mm/master-face ((t (:background "DimGrey"))))
     (mm/mirror-face ((t (:background "DimGrey"))))
     (mode-line ((t (:background "grey75" :foreground "black" :box (:line-width -1 :style released-button)))))
     (mode-line-buffer-id ((t (:bold t :weight bold))))
     (mode-line-emphasis ((t (:bold t :weight bold))))
     (mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
     (mode-line-inactive ((t (:background "grey30" :foreground "grey80" :box (:line-width -1 :color "grey40" :style nil) :weight light))))
     (modelinepos-column-warning ((t (:foreground "Red"))))
     (mouse ((t (nil))))
     (next-error ((t (:background "blue3"))))
     (nobreak-space ((t (:foreground "cyan" :underline t))))
     (ns-working-text-face ((t (:underline t))))
     (nxml-attribute-colon-face ((t (:foreground "#ACACFC"))))
     (nxml-attribute-local-name-face ((t (:foreground "#ACACFC"))))
     (nxml-attribute-prefix-face ((t (:foreground "#ACACFC"))))
     (nxml-attribute-value-delimiter-face ((t (:foreground "#00AD00"))))
     (nxml-attribute-value-face ((t (:foreground "#70F170"))))
     (nxml-cdata-section-CDATA-face ((t (:foreground "#ACACFC"))))
     (nxml-cdata-section-content-face ((t (nil))))
     (nxml-cdata-section-delimiter-face ((t (:foreground "#00AD00"))))
     (nxml-char-ref-delimiter-face ((t (:foreground "#00AD00"))))
     (nxml-char-ref-number-face ((t (:foreground "#00AD00"))))
     (nxml-comment-content-face ((t (:italic t :slant italic))))
     (nxml-comment-delimiter-face ((t (:foreground "#00AD00"))))
     (nxml-delimited-data-face ((t (:foreground "#70F170"))))
     (nxml-delimiter-face ((t (:foreground "#00AD00"))))
     (nxml-element-colon-face ((t (:foreground "#ACACFC"))))
     (nxml-element-local-name-face ((t (:foreground "#ACACFC"))))
     (nxml-element-prefix-face ((t (:foreground "#ACACFC"))))
     (nxml-entity-ref-delimiter-face ((t (:foreground "#00AD00"))))
     (nxml-entity-ref-name-face ((t (:foreground "#00AD00"))))
     (nxml-glyph-face ((t (:background "light grey" :foreground "black" :slant normal :weight normal))))
     (nxml-hash-face ((t (:foreground "#ACACFC"))))
     (nxml-heading-face ((t (:bold t :weight bold))))
     (nxml-markup-declaration-delimiter-face ((t (:foreground "#00AD00"))))
     (nxml-name-face ((t (:foreground "#ACACFC"))))
     (nxml-namespace-attribute-colon-face ((t (:foreground "#ACACFC"))))
     (nxml-namespace-attribute-prefix-face ((t (:foreground "#ACACFC"))))
     (nxml-namespace-attribute-value-delimiter-face ((t (:foreground "#00AD00"))))
     (nxml-namespace-attribute-value-face ((t (:foreground "#70F170"))))
     (nxml-namespace-attribute-xmlns-face ((t (:foreground "#ACACFC"))))
     (nxml-outline-active-indicator-face ((t (:stipple nil :background "unspecified-bg" :foreground "#dadada" :inverse-video nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "default" :family "default" :box 1 :height 1))))
     (nxml-outline-ellipsis-face ((t (:bold t :family "default" :foundry "default" :width normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#dadada" :background "unspecified-bg" :stipple nil :weight bold :height 1))))
     (nxml-outline-indicator-face ((t (:family "default" :foundry "default" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#dadada" :background "unspecified-bg" :stipple nil :height 1))))
     (nxml-processing-instruction-content-face ((t (:foreground "#70F170"))))
     (nxml-processing-instruction-delimiter-face ((t (:foreground "#00AD00"))))
     (nxml-processing-instruction-target-face ((t (:foreground "#ACACFC"))))
     (nxml-prolog-keyword-face ((t (:foreground "#ACACFC"))))
     (nxml-prolog-literal-content-face ((t (:foreground "#70F170"))))
     (nxml-prolog-literal-delimiter-face ((t (:foreground "#00AD00"))))
     (nxml-ref-face ((t (:foreground "#00AD00"))))
     (nxml-tag-delimiter-face ((t (:foreground "#00AD00"))))
     (nxml-tag-slash-face ((t (:foreground "#ACACFC"))))
     (nxml-text-face ((t (nil))))
     (org-agenda-calendar-event ((t (:family "default" :foundry "default" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#dadada" :background "unspecified-bg" :stipple nil :height 1))))
     (org-agenda-calendar-sexp ((t (:family "default" :foundry "default" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#dadada" :background "unspecified-bg" :stipple nil :height 1))))
     (org-agenda-clocking ((t (:background "SkyBlue4"))))
     (org-agenda-column-dateline ((t (:family "default" :weight normal :slant normal :underline nil :strike-through nil :background "grey30" :height 1))))
     (org-agenda-current-time ((t (:foreground "LightGoldenrod"))))
     (org-agenda-date ((t (:foreground "LightSkyBlue"))))
     (org-agenda-date-today ((t (:italic t :bold t :foreground "LightSkyBlue" :slant italic :weight bold))))
     (org-agenda-date-weekend ((t (:bold t :foreground "LightSkyBlue" :weight bold))))
     (org-agenda-diary ((t (:family "default" :foundry "default" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#dadada" :background "unspecified-bg" :stipple nil :height 1))))
     (org-agenda-dimmed-todo-face ((t (:foreground "grey50"))))
     (org-agenda-done ((t (:foreground "PaleGreen"))))
     (org-agenda-filter-category ((t (:box (:line-width -1 :style released-button) :foreground "black" :background "grey75"))))
     (org-agenda-filter-regexp ((t (:box (:line-width -1 :style released-button) :foreground "black" :background "grey75"))))
     (org-agenda-filter-tags ((t (:box (:line-width -1 :style released-button) :foreground "black" :background "grey75"))))
     (org-agenda-restriction-lock ((t (:background "skyblue4"))))
     (org-agenda-structure ((t (:foreground "LightSkyBlue"))))
     (org-archived ((t (:foreground "grey70"))))
     (org-block ((t (:foreground "grey70"))))
     (org-block-background ((t (nil))))
     (org-block-begin-line ((t (:foreground "gray53"))))
     (org-block-end-line ((t (:foreground "gray53"))))
     (org-checkbox ((t (:bold t :weight bold))))
     (org-checkbox-statistics-done ((t (:bold t :weight bold :foreground "PaleGreen"))))
     (org-checkbox-statistics-todo ((t (:bold t :weight bold :foreground "Pink"))))
     (org-clock-overlay ((t (:background "SkyBlue4"))))
     (org-code ((t (:foreground "grey70"))))
     (org-column ((t (:background "grey30" :strike-through nil :underline nil :slant normal :weight normal :height 1 :family "default"))))
     (org-column-title ((t (:bold t :background "grey30" :underline t :weight bold))))
     (org-date ((t (:foreground "Cyan" :underline t))))
     (org-date-selected ((t (:background "Pink"))))
     (org-default ((t (:family "default" :foundry "default" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#dadada" :background "unspecified-bg" :stipple nil :height 1))))
     (org-document-info ((t (:foreground "pale turquoise"))))
     (org-document-info-keyword ((t (:foreground "grey70"))))
     (org-document-title ((t (:bold t :foreground "pale turquoise" :weight bold))))
     (org-done ((t (:bold t :foreground "PaleGreen" :weight bold))))
     (org-drawer ((t (:foreground "LightSkyBlue"))))
     (org-ellipsis ((t (:foreground "LightGoldenrod" :underline t))))
     (org-footnote ((t (:foreground "Cyan" :underline t))))
     (org-formula ((t (:foreground "chocolate1"))))
     (org-headline-done ((t (:foreground "LightSalmon"))))
     (org-hide ((t (:foreground "black"))))
     (org-latex-and-related ((t (:foreground "burlywood"))))
     (org-level-1 ((t (:foreground "LightSkyBlue"))))
     (org-level-2 ((t (:foreground "LightGoldenrod"))))
     (org-level-3 ((t (:foreground "Cyan1"))))
     (org-level-4 ((t (:foreground "gray53"))))
     (org-level-5 ((t (:foreground "PaleGreen"))))
     (org-level-6 ((t (:foreground "Aquamarine"))))
     (org-level-7 ((t (:foreground "LightSteelBlue"))))
     (org-level-8 ((t (:foreground "LightSalmon"))))
     (org-link ((t (:underline t :foreground "cyan1"))))
     (org-list-dt ((t (:bold t :weight bold))))
     (org-macro ((t (:foreground "burlywood"))))
     (org-meta-line ((t (:foreground "gray53"))))
     (org-mode-line-clock ((t (:box (:line-width -1 :style released-button) :foreground "black" :background "grey75"))))
     (org-mode-line-clock-overrun ((t (:box (:line-width -1 :style released-button) :foreground "black" :background "red"))))
     (org-priority ((t (:foreground "Cyan1"))))
     (org-property-value ((t (nil))))
     (org-quote ((t (:foreground "grey70"))))
     (org-scheduled ((t (:foreground "PaleGreen"))))
     (org-scheduled-previously ((t (:foreground "chocolate1"))))
     (org-scheduled-today ((t (:foreground "PaleGreen"))))
     (org-sexp-date ((t (:foreground "Cyan"))))
     (org-special-keyword ((t (:foreground "Cyan1"))))
     (org-table ((t (:foreground "LightSkyBlue"))))
     (org-tag ((t (:bold t :weight bold))))
     (org-target ((t (:underline t))))
     (org-time-grid ((t (:foreground "LightGoldenrod"))))
     (org-todo ((t (:bold t :foreground "Pink" :weight bold))))
     (org-upcoming-deadline ((t (:foreground "chocolate1"))))
     (org-verbatim ((t (:foreground "grey70"))))
     (org-verse ((t (:foreground "grey70"))))
     (org-warning ((t (:bold t :foreground "Pink" :weight bold))))
     (outline-1 ((t (:foreground "LightSkyBlue"))))
     (outline-2 ((t (:foreground "LightGoldenrod"))))
     (outline-3 ((t (:foreground "Cyan1"))))
     (outline-4 ((t (:foreground "gray53"))))
     (outline-5 ((t (:foreground "PaleGreen"))))
     (outline-6 ((t (:foreground "Aquamarine"))))
     (outline-7 ((t (:foreground "LightSteelBlue"))))
     (outline-8 ((t (:foreground "LightSalmon"))))
     (popup-face ((t (:background "lightgray" :foreground "black"))))
     (popup-isearch-match ((t (:background "sky blue"))))
     (popup-menu-face ((t (:background "lightgray" :foreground "black"))))
     (popup-menu-selection-face ((t (:background "steelblue" :foreground "white"))))
     (popup-scroll-bar-background-face ((t (:background "gray"))))
     (popup-scroll-bar-foreground-face ((t (:background "black"))))
     (popup-tip-face ((t (:background "khaki1" :foreground "black"))))
     (query-replace ((t (:foreground "brown4" :background "palevioletred2"))))
     (region ((t (:background "blue3"))))
     (scroll-bar ((t (nil))))
     (secondary-selection ((t (:background "SkyBlue4"))))
     (shadow ((t (:foreground "grey70"))))
     (show-paren-match ((t (:background "steelblue3"))))
     (show-paren-mismatch ((t (:background "purple" :foreground "white"))))
     (success ((t (:bold t :foreground "Green1" :weight bold))))
     (tool-bar ((t (:foreground "black" :box (:line-width 1 :style released-button)))))
     (tooltip ((t (:family "Sans Serif" :background "lightyellow" :foreground "black"))))
     (trailing-whitespace ((t (:background "red1"))))
     (underline ((t (:bold t :weight bold))))
     (undo-tree-visualizer-active-branch-face ((t (:bold t :foreground "white" :weight bold))))
     (undo-tree-visualizer-current-face ((t (:foreground "red"))))
     (undo-tree-visualizer-default-face ((t (:foreground "gray"))))
     (undo-tree-visualizer-register-face ((t (:foreground "yellow"))))
     (undo-tree-visualizer-unmodified-face ((t (:foreground "cyan"))))
     (variable-pitch ((t (:family "Sans Serif"))))
     (vertical-border ((t (:weight light :box (:line-width -1 :color "grey40" :style nil) :foreground "grey80" :background "grey30"))))
     (visible-mark-face ((t (:underline "blue"))))
     (visible-mark-non-trailing-face0 ((t (:foreground "gray" :underline t))))
     (warning ((t (:bold t :foreground "DarkOrange" :weight bold))))
     (which-func ((t (:foreground "Blue1"))))
     (widget-button ((t (:bold t :weight bold))))
     (widget-button-pressed ((t (:foreground "red1"))))
     (widget-documentation ((t (:foreground "lime green"))))
     (widget-field ((t (:background "yellow3" :foreground "black"))))
     (widget-inactive ((t (:foreground "grey70"))))
     (widget-single-line-field ((t (:background "green3" :foreground "black"))))
     (yas/field-highlight-face ((t (:background "DimGrey"))))
     (yas/mirror-highlight-face ((t (:background "gray22")))))))
(add-to-list 'color-themes '(my-color-theme  "david.boon"))
