(eval-when-compile    (require 'color-theme))
(defun color-theme--dmb-late-night ()
  "Color theme by David M. Boon, created 2008-07-24."
  (interactive)
  (color-theme-install
   '(color-theme--dmb-late-night
     ((background-color . "#0C0914" ) ;; "#151C1F" "#191919"
      (background-mode . dark)
      (background-toolbar-color . "#000")
      (border-color . "#000")
      (bottom-toolbar-shadow-color . "#000")
      ;;(cursor-color . "#888")
      (cursor-color . "yellow")
      ;;(foreground-color . "#666")
      (foreground-color . "#EFF4FF")
      (mouse-color . "sienna1")
      (top-toolbar-shadow-color . "#111"))
     ((Man-overstrike-face . bold)
      (Man-reverse-face . highlight)
      (Man-underline-face . underline)
      (apropos-keybinding-face . underline)
      (apropos-label-face . italic)
      (apropos-match-face . match)
      (apropos-property-face . bold-italic)
      (apropos-symbol-face . bold)
      (compilation-message-face . underline)
      (display-time-mail-face . mode-line)
      (erc-interpret-mirc-color . t)
      (ibuffer-deletion-face . font-lock-type-face)
      (ibuffer-filter-group-name-face . bold)
      (ibuffer-marked-face . font-lock-warning-face)
      (ibuffer-title-face . font-lock-type-face)
      (list-matching-lines-buffer-name-face . underline)
      (list-matching-lines-face . match)
      (paren-match-face . paren-face-match)
      (paren-mismatch-face . paren-face-mismatch)
      (paren-no-match-face . paren-face-no-match)
      (ps-line-number-color . "black")
      (ps-zebra-color . 0.95)
      (tags-tag-face . default)
      (view-highlight-face . highlight)
      (widget-mouse-face . highlight))
     (default ((t (:bold t :stipple nil :background "#000" :foreground "#666" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight bold :height 83 :width normal :family "outline-consolas"))))
     (CUA-global-mark-face ((t (:background "cyan" :foreground "black"))))
     (CUA-rectangle-face ((t (:background "maroon" :foreground "white"))))
     (CUA-rectangle-noselect-face ((t (:background "dimgray" :foreground "white"))))
     (ansi-color-names-vector ((t (nil))))
     ;;(anything-header ((t (:bold t :background "PaleGoldenrod" :foreground "Black" :box nil :weight bold :width normal))))
     (anything-header ((t (:bold t :background "gray10" :foreground "grey35" :box nil :weight bold :width normal))))
     (anything-isearch-match ((t (:background "Yellow"))))
     (bg:erc-color-face0 ((t (nil))))
     (bg:erc-color-face1 ((t (nil))))
     (bg:erc-color-face10 ((t (nil))))
     (bg:erc-color-face11 ((t (nil))))
     (bg:erc-color-face12 ((t (nil))))
     (bg:erc-color-face13 ((t (nil))))
     (bg:erc-color-face14 ((t (nil))))
     (bg:erc-color-face15 ((t (nil))))
     (bg:erc-color-face2 ((t (nil))))
     (bg:erc-color-face3 ((t (nil))))
     (bg:erc-color-face4 ((t (nil))))
     (bg:erc-color-face5 ((t (nil))))
     (bg:erc-color-face6 ((t (nil))))
     (bg:erc-color-face7 ((t (nil))))
     (bg:erc-color-face8 ((t (nil))))
     (bg:erc-color-face9 ((t (nil))))
     (blue ((t (:foreground "blue"))))
     (bold ((t (:bold t :weight bold))))
     (bold-italic ((t (:bold t :weight bold))))
     (bookmark-menu-heading ((t (:bold t :weight bold :foreground "LightSlateGray"))))
     (border ((t (:background "#000"))))
     (border-glyph ((t (nil))))
     (buffer-menu-buffer ((t (:bold t :weight bold))))
     (buffer-menu-buffer-name ((t (:foreground "grey"))))
     (buffer-menu-current-buffer ((t (:background "Aquamarine" :foreground "Red"))))
     (buffer-menu-delete-mark ((t (:foreground "red4"))))
     (buffer-menu-directory-buffer ((t (:foreground "MediumTurquoise"))))
     (buffer-menu-file-name ((t (:foreground "PaleTurquoise4"))))
     (buffer-menu-flagged-buffer ((t (:foreground "red4"))))
     (buffer-menu-headings ((t (:background "DarkGreen" :foreground "Orange"))))
     (buffer-menu-marked-buffer ((t (:underline t))))
     (buffer-menu-mode ((t (:foreground "AntiqueWhite4"))))
     (buffer-menu-modified-mark ((t (:foreground "DarkOrange"))))
     (buffer-menu-read-only-mark ((t (:foreground "chocolate1"))))
     (buffer-menu-save-mark ((t (:background "Blue" :foreground "Orange"))))
     (buffer-menu-size ((t (:foreground "DarkSlateGrey"))))
     (buffer-menu-star-buffer ((t (:foreground "PaleTurquoise4"))))
     (buffer-menu-time ((t (:foreground "PaleTurquoise4"))))
     (buffer-menu-view-mark ((t (:background "Aquamarine" :foreground "Red"))))
     (buffers-tab ((t (:background "black" :foreground "white"))))
     (button ((t (:bold t :underline t :weight bold))))
     (c-nonbreakable-space-face ((t (:bold t :background "Red1" :weight bold))))
     (calendar-today-face ((t (:underline t))))
     (change-log-acknowledgement ((t (:foreground "grey67"))))
     (change-log-conditionals ((t (:foreground "darkseagreen"))))
     (change-log-date ((t (:foreground "PaleTurquoise4"))))
     (change-log-email ((t (:foreground "darkseagreen"))))
     (change-log-file ((t (:foreground "LightSteelBlue"))))
     (change-log-function ((t (:foreground "darkseagreen"))))
     (change-log-list ((t (:foreground "aquamarine3"))))
     (change-log-name ((t (:foreground "SlateGray3"))))
     (clearcase-dired-checkedout-face ((t (:foreground "red"))))
     ;;(comint-highlight-input ((t (:foreground "DarkSeaGreen"))))
     (comint-highlight-input ((t (:foreground "grey40"))))
     (comint-highlight-prompt ((t (:foreground "#6C8C56"))))  ;;ECE7BA
     (comint-input-face ((t (:foreground "deepskyblue"))))
     (compilation-column-number ((t (:foreground "LightSlateGray"))))
     (compilation-error ((t (:bold t :foreground "RosyBrown" :weight bold))))
     (compilation-info ((t (:foreground "LightSkyBlue"))))
     (compilation-line-number ((t (:foreground "darkseagreen" :underline nil))))
     (compilation-warning ((t (:bold t :foreground "Orange" :weight bold))))
     (completions-common-part ((t (nil))))
     (completions-first-difference ((t (nil))))
     (cperl-array-face ((t (:foreground "darkseagreen"))))
     (cperl-hash-face ((t (:foreground "darkseagreen"))))
     (cperl-nonoverridable-face ((t (:foreground "SkyBlue"))))
     (cscope-file-face ((t (:foreground "blue"))))
     (cscope-function-face ((t (:foreground "magenta"))))
     (cscope-line-face ((t (:foreground "green"))))
     (cscope-line-number-face ((t (:foreground "red"))))
     (cscope-mouse-face ((t (:background "blue" :foreground "white"))))
     (cursor ((t (:background "#888"))))
     (custom-button ((t (:bold t :foreground "#999" :weight bold))))
     (custom-button-mouse ((t (:background "grey90" :foreground "black" :box (:line-width 2 :style released-button)))))
     (custom-button-pressed ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style pressed-button)))))
     (custom-button-pressed-unraised ((t (:foreground "magenta4" :underline nil))))
     (custom-button-unraised ((t (:underline nil))))
     (custom-changed ((t (:background "blue" :foreground "white"))))
     (custom-comment ((t (:background "gray85"))))
     (custom-comment-tag ((t (:foreground "blue4"))))
     (custom-documentation ((t (nil))))
     (custom-face-tag ((t (:underline t))))
     (custom-group-tag ((t (:foreground "light blue" :underline t))))
     (custom-group-tag-1 ((t (:foreground "pink" :underline t))))
     (custom-invalid ((t (:background "red" :foreground "yellow"))))
     (custom-link ((t (:foreground "blue1" :underline t))))
     (custom-modified ((t (:background "blue" :foreground "white"))))
     (custom-rogue ((t (:background "black" :foreground "pink"))))
     (custom-saved ((t (:underline t))))
     (custom-set ((t (:background "white" :foreground "blue"))))
     (custom-state ((t (:foreground "lime green"))))
     (custom-themed ((t (:background "blue1" :foreground "white"))))
     (custom-variable-button ((t (:bold t :underline t :weight bold))))
     (custom-variable-tag ((t (:foreground "light blue" :underline t))))
     (custom-visibility ((t (:foreground "blue1" :underline t :height 0.8))))
     (cyan ((t (:foreground "cyan"))))
     (diary-face ((t (:foreground "IndianRed"))))
     (diff-added ((t (nil))))
     (diff-changed ((t (nil))))
     (diff-context ((t (:foreground "grey50"))))
     (diff-file-header ((t (:bold t :background "grey70" :weight bold))))
     (diff-function ((t (:background "grey85"))))
     (diff-header ((t (:background "grey85"))))
     (diff-hunk-header ((t (:background "grey85"))))
     (diff-index ((t (:bold t :background "grey70" :weight bold))))
     (diff-indicator-added ((t (nil))))
     (diff-indicator-changed ((t (nil))))
     (diff-indicator-removed ((t (nil))))
     (diff-nonexistent ((t (:bold t :background "grey70" :weight bold))))
     (diff-refine-change ((t (:background "grey90"))))
     (diff-removed ((t (nil))))
     (dired-directory ((t (:foreground "LightSkyBlue"))))
     (dired-face-boring ((t (:foreground "Gray65"))))
     (dired-face-directory ((t (:foreground "lightgreen"))))
     (dired-face-executable ((t (:foreground "indianred"))))
     (dired-face-flagged ((t (:background "LightSlateGray"))))
     (dired-face-marked ((t (:background "darkblue" :foreground "deepskyblue"))))
     (dired-face-permissions ((t (:background "darkblue" :foreground "white"))))
     (dired-face-setuid ((t (:foreground "Red"))))
     (dired-face-socket ((t (:foreground "magenta"))))
     (dired-face-symlink ((t (:foreground "grey95"))))
     (dired-flagged ((t (:foreground "RosyBrown3"))))
     (dired-header ((t (:foreground "LightGoldenrod"))))
     (dired-ignored ((t (:foreground "grey51"))))
     (dired-mark ((t (:foreground "SlateGray3"))))
     (dired-marked ((t (:foreground "IndianRed"))))
     (dired-symlink ((t (:foreground "aquamarine3"))))
     (dired-warn-writable ((t (:bold t :background "black" :foreground "grey75" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight bold :height 83 :width normal :family "outline-consolas"))))
     (dired-warning ((t (:bold t :foreground "RosyBrown" :weight bold))))
     (diredp-compressed-file-suffix ((t (:foreground "goldenrod"))))
     (diredp-date-time ((t (:foreground "gray50"))))
     (diredp-deletion ((t (:foreground "red4" ))))
     (diredp-deletion-file-name ((t (:foreground "Red"))))
     (diredp-dir-heading ((t (:foreground "goldenrod"))))
     (diredp-dir-priv ((t (:foreground "gray"))))
     (diredp-display-msg ((t (:foreground "Blue"))))
     (diredp-exec-priv ((t (:foreground "DarkGreen"))))
     (diredp-executable-tag ((t (:foreground "Red"))))
     ;;(diredp-file-name ((t (:foreground "black"))))
     (diredp-file-name ((t (:foreground "gray50"))))
     (diredp-file-suffix ((t (:foreground "grey57"))))
     (diredp-flag-mark ((t (:foreground "Yellow"))))
     (diredp-flag-mark-line ((t (:background "Skyblue"))))
     (diredp-ignored-file-name ((t (:foreground "#00006DE06DE0"))))
     (diredp-link-priv ((t (:foreground "DarkOrange"))))
     (diredp-no-priv ((t (:foreground "black"))))
     (diredp-other-priv ((t (:foreground "blue4"))))
     (diredp-rare-priv ((t (:foreground "Magenta"))))
     (diredp-read-priv ((t (:foreground "MidnightBlue"))))
     (diredp-symlink ((t (:foreground "DarkOrange"))))
     (diredp-write-priv ((t (:foreground "slate grey"))))
     (display-time-mail-balloon-enhance-face ((t (:background "orange"))))
     (display-time-mail-balloon-gnus-group-face ((t (:foreground "blue"))))
     (display-time-time-balloon-face ((t (:foreground "red"))))
     (dmb-blink-region-face ((t (:background "lavendar"))))
     (dmb-current-line-face ((t (:background "#2C932CDA4101"))))
     (dmb-face-five ((t (:foreground "IndianRed"))))
     (dmb-face-four ((t (:foreground "#997009"))))
     (dmb-face-hi-light-line-error ((t (:foreground "maroon"))))
     (dmb-face-ibuffer-elisp ((t (:foreground "SeaGreen"))))
     (dmb-face-ibuffer-grep ((t (:foreground "goldenrod4"))))
     (dmb-face-ibuffer-jde ((t (:foreground "LightSlateGray"))))
     (dmb-face-light-blue ((t (:foreground "LightSkyBlue"))))
     (dmb-face-one ((t (:foreground "midnight blue"))))
     (dmb-face-onex ((t (:foreground "LightSkyBlue"))))
     (dmb-face-six ((t (:foreground "DarkSlateBlue"))))
     (dmb-face-three ((t (:foreground "DarkSeaGreen"))))
     (dmb-face-two ((t (:foreground "medium sea green"))))
     (dmb-grep-hit-face ((t (:foreground "LightSlateGray"))))
     (dmb-grep-match-face ((t (:foreground "DarkSlateBlue" :underline nil))))
     (dmb-mark-face ((t (:foreground "cyan" :underline nil))))
     ;;(dmb-mode-line-directory-face ((t (:foreground "dark slate gray"))))
     (dmb-notes-txt-face ((t (:foreground "DodgerBlue" :underline nil))))
     (ecb-bucket-node-face ((t (:bold t :weight bold :height 1.0))))
     (ecb-default-general-face ((t (:height 1.0))))
     (ecb-default-highlight-face ((t (:background "cornflower blue" :foreground "yellow"))))
     (ecb-directories-general-face ((t (:height 1.0))))
     (ecb-directory-face ((t (:background "cornflower blue" :foreground "yellow"))))
     (ecb-directory-not-accessible-face ((t (:foreground "gray60" :height 1.0))))
     (ecb-history-face ((t (:background "cornflower blue" :foreground "yellow"))))
     (ecb-history-general-face ((t (:height 1.0))))
     (ecb-method-face ((t (:background "cornflower blue" :foreground "yellow"))))
     (ecb-method-non-semantic-face ((t (:foreground "brown" :height 1.0))))
     (ecb-methods-general-face ((t (:height 1.0))))
     (ecb-mode-line-data-face ((t (nil))))
     (ecb-mode-line-prefix-face ((t (:foreground "forestgreen"))))
     (ecb-mode-line-win-nr-face ((t (:bold t :weight bold))))
     (ecb-source-face ((t (:background "cornflower blue" :foreground "yellow"))))
     (ecb-source-in-directories-buffer-face ((t (:foreground "medium blue" :height 1.0))))
     (ecb-source-read-only-face ((t (:italic t :slant italic))))
     (ecb-sources-general-face ((t (:height 1.0))))
     (ecb-tag-header-face ((t (:background "SeaGreen1"))))
     (ecb-tree-guide-line-face ((t (:foreground "grey" :height 1.0))))
     (ecb-type-tag-class-face ((t (:bold t :weight bold))))
     (ecb-type-tag-enum-face ((t (:bold t :weight bold))))
     (ecb-type-tag-group-face ((t (:bold t :foreground "dim gray" :weight bold))))
     (ecb-type-tag-interface-face ((t (:bold t :weight bold))))
     (ecb-type-tag-struct-face ((t (:bold t :weight bold))))
     (ecb-type-tag-typedef-face ((t (:bold t :weight bold))))
     (ecb-type-tag-union-face ((t (:bold t :weight bold))))
     (ediff-current-diff-A ((t (:background "#b38080" :foreground "grey"))))
     (ediff-current-diff-Ancestor ((t (:background "VioletRed" :foreground "Black"))))
     (ediff-current-diff-B ((t (:background "#2c6a8f" :foreground "grey"))))
     (ediff-current-diff-C ((t (:background "Pink" :foreground "Navy"))))
     (ediff-current-diff-face-A ((t (:background "pale green" :foreground "firebrick"))))
     (ediff-current-diff-face-Ancestor ((t (:background "VioletRed" :foreground "Black"))))
     (ediff-current-diff-face-B ((t (:background "Yellow" :foreground "DarkOrchid"))))
     (ediff-current-diff-face-C ((t (:background "Pink" :foreground "Navy"))))
     (ediff-even-diff-A ((t (:foreground "grey51"))))
     (ediff-even-diff-Ancestor ((t (:background "Grey" :foreground "White"))))
     (ediff-even-diff-B ((t (:foreground "grey51"))))
     (ediff-even-diff-C ((t (:background "light grey" :foreground "Black"))))
     (ediff-even-diff-face-A ((t (:background "light grey" :foreground "Black"))))
     (ediff-even-diff-face-Ancestor ((t (:background "Grey" :foreground "White"))))
     (ediff-even-diff-face-B ((t (:background "Grey" :foreground "White"))))
     (ediff-even-diff-face-C ((t (:background "light grey" :foreground "Black"))))
     (ediff-fine-diff-A ((t (:background "pale goldenrod" :foreground "black"))))
     (ediff-fine-diff-Ancestor ((t (:background "Green" :foreground "Black"))))
     (ediff-fine-diff-B ((t (:background "pale goldenrod" :foreground "black"))))
     (ediff-fine-diff-C ((t (:background "Turquoise" :foreground "Black"))))
     (ediff-fine-diff-face-A ((t (:background "sky blue" :foreground "Navy"))))
     (ediff-fine-diff-face-Ancestor ((t (:background "Green" :foreground "Black"))))
     (ediff-fine-diff-face-B ((t (:background "cyan" :foreground "Black"))))
     (ediff-fine-diff-face-C ((t (:background "Turquoise" :foreground "Black"))))
     (ediff-odd-diff-A ((t (:background "grey26"))))
     (ediff-odd-diff-Ancestor ((t (:background "gray40" :foreground "cyan3"))))
     (ediff-odd-diff-B ((t (:background "grey26"))))
     (ediff-odd-diff-C ((t (:background "Grey" :foreground "White"))))
     (ediff-odd-diff-face-A ((t (:background "Grey" :foreground "White"))))
     (ediff-odd-diff-face-Ancestor ((t (:background "light grey" :foreground "Black"))))
     (ediff-odd-diff-face-B ((t (:background "light grey" :foreground "Black"))))
     (ediff-odd-diff-face-C ((t (:background "Grey" :foreground "White"))))
     (eieio-custom-slot-tag-face ((t (:foreground "blue"))))
     (eldoc-highlight-function-argument ((t (:bold t :weight bold))))
     (erc-action-face ((t (nil))))
     (erc-bold-face ((t (:bold t :weight bold))))
     (erc-command-indicator-face ((t (:bold t :weight bold))))
     (erc-current-nick-face ((t (:bold t :weight bold))))
     (erc-default-face ((t (nil))))
     (erc-direct-msg-face ((t (nil))))
     (erc-error-face ((t (:bold t :foreground "IndianRed" :weight bold))))
     (erc-header-line ((t (:background "grey90" :foreground "grey20"))))
     (erc-highlight-face ((t (:bold t :foreground "pale green" :weight bold))))
     (erc-input-face ((t (:foreground "#555"))))
     (erc-inverse-face ((t (:background "steel blue" :foreground "darkslategrey"))))
     (erc-keyword-face ((t (:bold t :foreground "#999" :weight bold))))
     (erc-my-nick-face ((t (:bold t :foreground "brown" :weight bold))))
     (erc-nick-default-face ((t (:bold t :weight bold))))
     (erc-nick-msg-face ((t (:foreground "#888"))))
     (erc-notice-face ((t (:foreground "#444"))))
     (erc-pal-face ((t (:foreground "#888"))))
     (erc-prompt-face ((t (:bold t :foreground "#777" :weight bold))))
     (erc-timestamp-face ((t (:bold t :foreground "#777" :weight bold))))
     (erc-underline-face ((t (:underline t))))
     (escape-glyph ((t (:foreground "brown"))))
     (eshell-ls-archive-face ((t (:bold t :foreground "IndianRed" :weight bold))))
     (eshell-ls-backup-face ((t (:foreground "Grey"))))
     (eshell-ls-clutter-face ((t (:foreground "DimGray"))))
     (eshell-ls-directory-face ((t (:bold t :foreground "MediumSlateBlue" :weight bold))))
     (eshell-ls-executable-face ((t (:foreground "Coral"))))
     (eshell-ls-missing-face ((t (:foreground "black"))))
     (eshell-ls-picture-face ((t (:foreground "Violet"))))
     (eshell-ls-product-face ((t (:foreground "sandybrown"))))
     (eshell-ls-readonly-face ((t (:foreground "Aquamarine"))))
     (eshell-ls-special-face ((t (:foreground "Gold"))))
     (eshell-ls-symlink-face ((t (:foreground "White"))))
     (eshell-ls-unreadable-face ((t (:foreground "DimGray"))))
     (eshell-prompt-face ((t (:foreground "MediumAquamarine"))))
     (eshell-test-failed-face ((t (:bold t :foreground "OrangeRed" :weight bold))))
     (eshell-test-ok-face ((t (:bold t :foreground "Green" :weight bold))))
     (excerpt ((t (:italic t :slant italic))))
     (ffap ((t (:background "darkolivegreen"))))
     (fg:erc-color-face0 ((t (:foreground "white"))))
     (fg:erc-color-face1 ((t (:foreground "beige"))))
     (fg:erc-color-face10 ((t (:foreground "pale goldenrod"))))
     (fg:erc-color-face11 ((t (:foreground "light goldenrod yellow"))))
     (fg:erc-color-face12 ((t (:foreground "light yellow"))))
     (fg:erc-color-face13 ((t (:foreground "yellow"))))
     (fg:erc-color-face14 ((t (:foreground "light goldenrod"))))
     (fg:erc-color-face15 ((t (:foreground "lime green"))))
     (fg:erc-color-face2 ((t (:foreground "lemon chiffon"))))
     (fg:erc-color-face3 ((t (:foreground "light cyan"))))
     (fg:erc-color-face4 ((t (:foreground "powder blue"))))
     (fg:erc-color-face5 ((t (:foreground "sky blue"))))
     (fg:erc-color-face6 ((t (:foreground "dark sea green"))))
     (fg:erc-color-face7 ((t (:foreground "pale green"))))
     (fg:erc-color-face8 ((t (:foreground "medium spring green"))))
     (fg:erc-color-face9 ((t (:foreground "khaki"))))
     (file-name-shadow ((t (:foreground "LightSlateGray"))))
     (fixed ((t (:bold t :weight bold))))
     (fixed-pitch ((t (:family "courier"))))
     (fl-comment-face ((t (:foreground "pink"))))
     (fl-doc-string-face ((t (:foreground "purple"))))
     (fl-function-name-face ((t (:foreground "red"))))
     (fl-keyword-face ((t (:foreground "cadetblue"))))
     (fl-string-face ((t (:foreground "green"))))
     (fl-type-face ((t (:foreground "yellow"))))
     (flash-paren-face-off ((t (nil))))
     (flash-paren-face-on ((t (nil))))
     (flash-paren-face-region ((t (nil))))
     (flymake-errline ((t (:underline "OrangeRed"))))
     (flymake-warnline ((t (:underline "DarkSlateBlue"))))
     (flyspell-duplicate-face ((t (:bold t :foreground "Gold3" :underline t :weight bold))))
     (flyspell-incorrect-face ((t (:bold t :foreground "OrangeRed" :underline t :weight bold))))
     (font-latex-bold-face ((t (:bold t :foreground "DarkOliveGreen" :weight bold))))
     (font-latex-italic-face ((t (:italic t :foreground "DarkOliveGreen" :slant italic))))
     (font-latex-math-face ((t (:foreground "burlywood"))))
     (font-latex-sedate-face ((t (:foreground "LightGray"))))
     (font-latex-string-face ((t (:foreground "RosyBrown"))))
     (font-latex-warning-face ((t (:bold t :foreground "Red" :weight bold))))
     (font-lock-builtin-face ((t (:bold t :foreground "#777" :weight bold))))
     (font-lock-comment-delimiter-face ((t (:bold t :foreground "grey67" :weight bold))))
     ;;(font-lock-comment-face ((t (:foreground "#555"))))
     (font-lock-comment-face ((t (:foreground "#75715E"))))
     
     (font-lock-constant-face ((t (:foreground "#777"))))
     (font-lock-doc-face ((t (:foreground "#777"))))
     (font-lock-doc-string-face ((t (:foreground "#777"))))
     (font-lock-function-name-face ((t (:bold t :foreground "#94C6F2" :weight bold))))
     (font-lock-keyword-face ((t (:foreground "#777"))))
     (font-lock-negation-char-face ((t (nil))))
     (font-lock-other-emphasized-face ((t (:bold t :foreground "gold1" :weight bold))))
     (font-lock-other-type-face ((t (:bold t :foreground "gold1" :weight bold))))
     (font-lock-preprocessor-face ((t (:foreground "#777"))))
     (font-lock-reference-face ((t (:foreground "#777"))))
     (font-lock-regexp-grouping-backslash ((t (:bold t :weight bold))))
     (font-lock-regexp-grouping-construct ((t (:bold t :weight bold))))
     ;;(font-lock-string-face ((t (:foreground "#7D8F84"))))
     ;;(font-lock-string-face ((t (:foreground "#405950"))))
     (font-lock-string-face ((t (:foreground "#C1C1C2"))))
     ;;(font-lock-string-face ((t (:foreground "#A69E86"))))
     ;;(font-lock-string-face ((t (:foreground "#777"))))
     (font-lock-type-face ((t (:bold t :foreground "LightSlateGray" :weight bold))))
     (font-lock-variable-name-face ((t (:bold t :foreground "#607685" :weight bold))))
     (font-lock-warning-face ((t (:bold t :foreground "#999" :weight bold))))
     (fringe ((t (:background "#111" :foreground "#444"))))
     (gdb-arrow-face ((t (:bold t :background "yellow" :foreground "red" :weight bold))))
     (gnus-cite-attribution-face ((t (:foreground "#bbb"))))
     (gnus-cite-face-1 ((t (:bold t :foreground "#aaa" :weight bold))))
     (gnus-cite-face-10 ((t (:foreground "medium purple"))))
     (gnus-cite-face-11 ((t (:foreground "turquoise"))))
     (gnus-cite-face-2 ((t (:bold t :foreground "#aaa" :weight bold))))
     (gnus-cite-face-3 ((t (:bold t :foreground "#aaa" :weight bold))))
     (gnus-cite-face-4 ((t (:foreground "#aaa"))))
     (gnus-cite-face-5 ((t (:foreground "#aaa"))))
     (gnus-cite-face-6 ((t (:bold t :foreground "#aaa" :weight bold))))
     (gnus-cite-face-7 ((t (:foreground "#aaa"))))
     (gnus-cite-face-8 ((t (:foreground "#aaa"))))
     (gnus-cite-face-9 ((t (:foreground "#aaa"))))
     (gnus-emphasis-bold ((t (:bold t :weight bold))))
     (gnus-emphasis-bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (gnus-emphasis-highlight-words ((t (:background "black" :foreground "#ccc"))))
     (gnus-emphasis-italic ((t (:italic t :slant italic))))
     (gnus-emphasis-underline ((t (:underline t))))
     (gnus-emphasis-underline-bold ((t (:bold t :underline t :weight bold))))
     (gnus-emphasis-underline-bold-italic ((t (:italic t :bold t :underline t :slant italic :weight bold))))
     (gnus-emphasis-underline-italic ((t (:italic t :underline t :slant italic))))
     (gnus-group-mail-1-empty-face ((t (:foreground "#999"))))
     (gnus-group-mail-1-face ((t (:bold t :foreground "#999" :weight bold))))
     (gnus-group-mail-2-empty-face ((t (:foreground "#999"))))
     (gnus-group-mail-2-face ((t (:bold t :foreground "#999" :weight bold))))
     (gnus-group-mail-3-empty-face ((t (:foreground "#888"))))
     (gnus-group-mail-3-face ((t (:bold t :foreground "#888" :weight bold))))
     (gnus-group-mail-low-empty-face ((t (:foreground "#777"))))
     (gnus-group-mail-low-face ((t (:bold t :foreground "#777" :weight bold))))
     (gnus-group-news-1-empty-face ((t (:foreground "#999"))))
     (gnus-group-news-1-face ((t (:bold t :foreground "#999" :weight bold))))
     (gnus-group-news-2-empty-face ((t (:foreground "#888"))))
     (gnus-group-news-2-face ((t (:bold t :foreground "#888" :weight bold))))
     (gnus-group-news-3-empty-face ((t (:foreground "#777"))))
     (gnus-group-news-3-face ((t (:bold t :foreground "#777" :weight bold))))
     (gnus-group-news-4-empty-face ((t (:foreground "#666"))))
     (gnus-group-news-4-face ((t (:bold t :foreground "#666" :weight bold))))
     (gnus-group-news-5-empty-face ((t (:foreground "#666"))))
     (gnus-group-news-5-face ((t (:bold t :foreground "#666" :weight bold))))
     (gnus-group-news-6-empty-face ((t (:foreground "#666"))))
     (gnus-group-news-6-face ((t (:bold t :foreground "#666" :weight bold))))
     (gnus-group-news-low-empty-face ((t (:foreground "#666"))))
     (gnus-group-news-low-face ((t (:bold t :foreground "#666" :weight bold))))
     (gnus-header-content-face ((t (:foreground "#888"))))
     (gnus-header-from-face ((t (:bold t :foreground "#888" :weight bold))))
     (gnus-header-name-face ((t (:bold t :foreground "#777" :weight bold))))
     (gnus-header-newsgroups-face ((t (:bold t :foreground "#777" :weight bold))))
     (gnus-header-subject-face ((t (:bold t :foreground "#999" :weight bold))))
     (gnus-picons-face ((t (:background "white" :foreground "black"))))
     (gnus-picons-xbm-face ((t (:background "white" :foreground "black"))))
     (gnus-signature-face ((t (:bold t :foreground "#444" :weight bold))))
     (gnus-splash-face ((t (:foreground "#ccc"))))
     (gnus-summary-cancelled-face ((t (:background "#555" :foreground "#000"))))
     (gnus-summary-high-ancient-face ((t (:bold t :foreground "#555" :weight bold))))
     (gnus-summary-high-read-face ((t (:bold t :foreground "#666" :weight bold))))
     (gnus-summary-high-ticked-face ((t (:bold t :foreground "#777" :weight bold))))
     (gnus-summary-high-unread-face ((t (:bold t :foreground "#888" :weight bold))))
     (gnus-summary-low-ancient-face ((t (:foreground "#444"))))
     (gnus-summary-low-read-face ((t (:foreground "#555"))))
     (gnus-summary-low-ticked-face ((t (:foreground "#666"))))
     (gnus-summary-low-unread-face ((t (:foreground "#777"))))
     (gnus-summary-normal-ancient-face ((t (:foreground "#555"))))
     (gnus-summary-normal-read-face ((t (:foreground "#666"))))
     (gnus-summary-normal-ticked-face ((t (:foreground "#777"))))
     (gnus-summary-normal-unread-face ((t (:foreground "#888"))))
     (gnus-summary-selected-face ((t (:background "#333" :underline t))))
     (gnus-x-face ((t (:background "white" :foreground "black"))))
     (green ((t (:foreground "green"))))
     (gui-button-face ((t (:background "grey75" :foreground "black"))))
     (gui-element ((t (:background "#D4D0C8" :foreground "black"))))
     (header-line ((t (:background "#333" :foreground "#000" :box nil :width normal))))
     (help-argument-name ((t (nil))))
     (hi-black-b ((t (:bold t :weight bold))))
     (hi-black-hb ((t (:bold t :weight bold :height 1.67 :family "helv"))))
     (hi-blue ((t (:background "light blue"))))
     (hi-blue-b ((t (:bold t :foreground "blue1" :weight bold))))
     (hi-green ((t (:foreground "PaleGreen2"))))
     (hi-green-b ((t (:bold t :foreground "green1" :weight bold))))
     (hi-indian-red ((t (:background "IndianRed1"))))
     (hi-indian-red-fg ((t (:foreground "IndianRed1"))))
     (hi-lemon-chiffon ((t (:background "lemon chiffon"))))
     (hi-light-goldenrod ((t (:background "light goldenrod"))))
     (hi-pink ((t (:background "pink"))))
     (hi-red-b ((t (:bold t :foreground "red1" :weight bold))))
     (hi-yellow ((t (:background "yellow1"))))
     (highlight ((t (:background "dark slate blue" :foreground "light blue"))))
     (highlight-changes-delete-face ((t (:foreground "red" :underline t))))
     (highlight-changes-face ((t (:foreground "red"))))
     (highlight-current-line-face ((t (:background "#084B0469146E"))))
     (highline-face ((t (:background "#3d3e47"))))
     (highline-vertical-face ((t (:background "darkslateblue"))))
     (holiday-face ((t (:background "#000" :foreground "#777"))))
     (hyper-apropos-documentation ((t (:foreground "#aaaaaa"))))
     (hyper-apropos-heading ((t (:bold t :foreground "#999999" :weight bold))))
     (hyper-apropos-hyperlink ((t (:foreground "Violet"))))
     (hyper-apropos-major-heading ((t (:bold t :foreground "#ff0000" :weight bold))))
     (hyper-apropos-section-heading ((t (:italic t :bold t :foreground "#33aa55" :slant italic :weight bold))))
     (hyper-apropos-warning ((t (:bold t :foreground "red" :weight bold))))
     (ibuffer-deletion-face ((t (:foreground "red"))))
     (ibuffer-filter-group-name-face ((t (:foreground "dark slate gray"))))
     (ibuffer-marked-face ((t (:foreground "green"))))
     (icicle-Completions-instruction-1 ((t (:foreground "#AC4AAC4A0000"))))
     (icicle-Completions-instruction-2 ((t (:foreground "#0000D53CD53C"))))
     (icicle-candidate-part ((t (:background "#451700143197"))))
     (icicle-common-match-highlight-Completions ((t (:foreground "#2017A71F2017"))))
     (icicle-complete-input ((t (:foreground "#B19E6A64B19E"))))
     (icicle-completion ((t (:foreground "#0000D53CD53C"))))
     (icicle-current-candidate-highlight ((t (:background "#69D40A460000"))))
     (icicle-historical-candidate ((t (:foreground "#DBD599DF0000"))))
     (icicle-input-completion-fail ((t (:background "#22225F5F2222"))))
     (icicle-input-completion-fail-lax ((t (:background "#00005E3B5A8D"))))
     (icicle-match-highlight-Completions ((t (:foreground "#1F1FA21CA21C"))))
     (icicle-match-highlight-minibuffer ((t (:underline t))))
     (icicle-multi-command-completion ((t (:background "#8B3500007533" :foreground "#0000D53CD53C"))))
     (icicle-mustmatch-completion ((t (:box (:line-width 2 :color "Blue")))))
     (icicle-proxy-candidate ((t (:background "#316B22970000"))))
     (icicle-saved-candidate ((t (:background "gray20"))))
     (icicle-search-context-level-1 ((t (:background "#FA6CC847FFFF"))))
     (icicle-search-context-level-2 ((t (:background "#C847FFFFE423"))))
     (icicle-search-context-level-3 ((t (:background "#C847D8FEFFFF"))))
     (icicle-search-context-level-4 ((t (:background "#EF47FFFFC847"))))
     (icicle-search-context-level-5 ((t (:background "#FCFCE1E1FFFF"))))
     (icicle-search-context-level-6 ((t (:background "#E1E1FFFFF0F0"))))
     (icicle-search-context-level-7 ((t (:background "#E1E1EAEAFFFF"))))
     (icicle-search-context-level-8 ((t (:background "#F6F5FFFFE1E1"))))
     (icicle-search-current-input ((t (:background "#7F0D00007F0D" :foreground "White"))))
     (icicle-search-main-regexp-current ((t (:background "#00004AA652F1"))))
     (icicle-search-main-regexp-others ((t (:background "#348608690000"))))
     (icicle-special-candidate ((t (:background "#176900004E0A"))))
     (icicle-whitespace-highlight ((t (:background "#000093F402A2"))))
     (ido-first-match ((t (:bold t :weight bold))))
     (ido-incomplete-regexp ((t (:bold t :foreground "RosyBrown" :weight bold))))
     (ido-indicator ((t (:background "red1" :foreground "yellow1" :width condensed))))
     (ido-only-match ((t (:foreground "ForestGreen"))))
     (ido-subdir ((t (:foreground "red1"))))
     (info-elisp-command-ref-item ((t (:background "LightGray" :foreground "Blue"))))
     (info-elisp-function-ref-item ((t (:background "LightGray" :foreground "DarkBlue"))))
     (info-elisp-macro-ref-item ((t (:background "LightGray" :foreground "DarkMagenta"))))
     (info-elisp-reference-item ((t (:background "LightGray"))))
     (info-elisp-special-form-ref-item ((t (:background "LightGray" :foreground "DarkMagenta"))))
     (info-elisp-syntax-class-item ((t (:background "LightGray" :foreground "DarkGreen"))))
     (info-elisp-user-option-ref-item ((t (:background "LightGray" :foreground "Red"))))
     (info-elisp-variable-ref-item ((t (:background "LightGray" :foreground "FireBrick"))))
     (info-file ((t (:background "LightGray" :foreground "DarkBlue"))))
     (info-header-node ((t (:bold t :foreground "#666" :underline t :weight bold))))
     (info-header-xref ((t (:foreground "#666" :underline t))))
     (info-menu ((t (:foreground "Blue"))))
     (info-menu-header ((t (:bold t :foreground "#666" :weight bold :family "helv"))))
     (info-menu-star ((t (:underline t))))
     (info-node ((t (:bold t :foreground "#888" :underline t :weight bold))))
     (info-quoted-name ((t (:foreground "yellow"))))
     (info-string ((t (:foreground "red3"))))
     (info-title-1 ((t (:bold t :background "LightGray" :foreground "DarkBlue" :weight bold :height 1.728 :family "helv"))))
     (info-title-2 ((t (:bold t :background "LightGray" :foreground "Firebrick" :weight bold :height 1.44 :family "helv"))))
     (info-title-3 ((t (:bold t :background "LightGray" :foreground "DarkGreen" :weight bold :height 1.2 :family "helv"))))
     (info-title-4 ((t (:bold t :background "LightGray" :foreground "DarkMagenta" :weight bold :family "helv"))))
     (info-xref ((t (:bold t :foreground "#777" :underline t :weight bold))))
     (info-xref-visited ((t (:foreground "magenta4" :underline t))))
     (isearch ((t (:background "#BF0F30" :foreground "pink"))))
     (isearch-fail ((t (:background "red4" :foreground "Black"))))
     (isearch-secondary ((t (:background "DimGray" :foreground "gray"))))
     (iswitchb-current-match ((t (:foreground "LightSkyBlue"))))
     (iswitchb-invalid-regexp ((t (:bold t :foreground "RosyBrown" :weight bold))))
     (iswitchb-single-match ((t (:foreground "IndianRed"))))
     (iswitchb-virtual-matches ((t (:foreground "LightSteelBlue"))))
     (italic ((t (:bold t :weight bold))))
     (jabber-activity-face ((t (:bold t :foreground "red" :weight bold))))
     (jabber-chat-error ((t (:bold t :foreground "red" :weight bold))))
     (jabber-chat-prompt-foreign ((t (:bold t :foreground "red" :weight bold))))
     (jabber-chat-prompt-local ((t (:bold t :foreground "blue" :weight bold))))
     (jabber-chat-prompt-system ((t (:bold t :foreground "green" :weight bold))))
     (jabber-chat-text-foreign ((t (nil))))
     (jabber-chat-text-local ((t (nil))))
     (jabber-rare-time-face ((t (:foreground "darkgreen" :underline t))))
     (jabber-roster-user-away ((t (:italic t :foreground "dark green" :slant italic :weight normal))))
     (jabber-roster-user-chatty ((t (:bold t :foreground "dark orange" :slant normal :weight bold))))
     (jabber-roster-user-dnd ((t (:italic t :foreground "red" :slant italic :weight normal))))
     (jabber-roster-user-error ((t (:italic t :foreground "red" :slant italic :weight light))))
     (jabber-roster-user-offline ((t (:italic t :foreground "dark grey" :slant italic :weight light))))
     (jabber-roster-user-online ((t (:bold t :foreground "blue" :slant normal :weight bold))))
     (jabber-roster-user-xa ((t (:italic t :foreground "black" :slant italic :weight normal))))
     (jabber-title-large ((t (:bold t :weight bold :height 3.0 :width ultra-expanded :family "helv"))))
     (jabber-title-medium ((t (:bold t :weight bold :height 2.0 :width expanded :family "helv"))))
     (jabber-title-small ((t (:bold t :weight bold :height 1.0 :width semi-expanded :family "helv"))))
     (jde-bug-breakpoint-cursor ((t (:background "brown" :foreground "cyan"))))
     (jde-db-active-breakpoint-face ((t (:background "red" :foreground "black"))))
     (jde-db-requested-breakpoint-face ((t (:background "yellow" :foreground "black"))))
     (jde-db-spec-breakpoint-face ((t (:background "green" :foreground "black"))))
     (jde-java-font-lock-api-face ((t (:foreground "dark goldenrod"))))
     (jde-java-font-lock-bold-face ((t (:bold t :weight bold))))
     (jde-java-font-lock-code-face ((t (nil))))
     (jde-java-font-lock-constant-face ((t (:foreground "SlateGray3"))))
     (jde-java-font-lock-doc-tag-face ((t (:foreground "DarkSeaGreen"))))
     (jde-java-font-lock-italic-face ((t (:italic t :slant italic))))
     (jde-java-font-lock-link-face ((t (:foreground "bisque"))))
     (jde-java-font-lock-modifier-face ((t (:foreground "MediumTurquoise"))))
     (jde-java-font-lock-number-face ((t (:foreground "RosyBrown"))))
     (jde-java-font-lock-operator-face ((t (:foreground "medium blue"))))
     (jde-java-font-lock-package-face ((t (:foreground "blue3"))))
     (jde-java-font-lock-pre-face ((t (nil))))
     (jde-java-font-lock-private-face ((t (:foreground "Orchid"))))
     (jde-java-font-lock-protected-face ((t (:foreground "Orchid"))))
     (jde-java-font-lock-public-face ((t (:foreground "Orchid"))))
     (jde-java-font-lock-underline-face ((t (:underline t))))
     (lazy-highlight ((t (:foreground "cornflower blue"))))
     (left-margin ((t (nil))))
     (link ((t (:foreground "blue1" :underline t))))
     (link-visited ((t (:foreground "magenta4" :underline t))))
     (list-mode-item-selected ((t (:background "gray68" :foreground "white"))))
     (magenta ((t (:foreground "magenta"))))
     (makefile-space-face ((t (:background "hotpink"))))
     (match ((t (:background "yellow1"))))
     (mb-depth-indicator ((t (:bold t :family "outline-consolas" :width normal :weight bold :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#666" :background "#000" :stipple nil :height 83))))
     (menu ((t (:background "#111" :foreground "#444"))))
     (message-cited-text-face ((t (:bold t :foreground "#aaa" :weight bold))))
     (message-header-cc-face ((t (:bold t :foreground "#888" :weight bold))))
     (message-header-name-face ((t (:bold t :foreground "#777" :weight bold))))
     (message-header-newsgroups-face ((t (:bold t :foreground "#777" :weight bold))))
     (message-header-other-face ((t (:bold t :foreground "#666" :weight bold))))
     (message-header-subject-face ((t (:bold t :foreground "#999" :weight bold))))
     (message-header-to-face ((t (:bold t :foreground "#777" :weight bold))))
     (message-header-xheader-face ((t (:bold t :foreground "#666" :weight bold))))
     (message-mml-face ((t (:bold t :foreground "Green3" :weight bold))))
     (message-separator-face ((t (:foreground "#999"))))
     (minibuffer-prompt ((t (:foreground "#929292"))))
     (moccur-current-line-face ((t (:underline t))))
     (moccur-face ((t (:bold t :background "light cyan" :weight bold))))
     (mode-line ((t (:background "#0C0914"  :foreground "#444" :overline "black"))))
     ;;(mode-line ((t (:foreground "black" :overline "LightGray"))))  ;;:background "GhostWhite" ;;:background "gray91"
     ;;(mode-line-buffer-id ((t (:background "#000" :foreground "#555"))))
     (mode-line-buffer-id ((t ( :foreground "#a3de5b"))))
     (mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
     (mode-line-inactive ((t (:background "#000" :foreground "#444" :overline "SteelBlue4"))))
     (modeline-mousable ((t (:background "#000" :foreground "#555"))))
     (modeline-mousable-minor-mode ((t (:background "#000" :foreground "#555"))))
     (mouse ((t (:background "sienna1"))))
     (mouse-flash-position ((t (:background "Yellow"))))
     (mouse-scan-lines ((t (:background "Yellow"))))
     (mumamo-background-chunk-major ((t (nil))))
     (mumamo-background-chunk-submode ((t (nil))))
     (my-tab-face ((t (:background "SlateBlue1"))))
     (next-error ((t (:background "blue4" :foreground "CadetBlue3"))))
     (nobreak-space ((t (:foreground "brown" :underline t))))
     (nxml-attribute-colon ((t (nil))))
     (nxml-attribute-local-name ((t (:bold t :weight bold :foreground "#888"))))
     (nxml-attribute-prefix ((t (:bold t :foreground "#777" :weight bold))))
     (nxml-attribute-value ((t (:foreground "grey"))))
     (nxml-attribute-value-delimiter ((t (:foreground "#777"))))
     (nxml-cdata-section-CDATA ((t (:bold t :foreground "#777" :weight bold))))
     (nxml-cdata-section-content ((t (nil))))
     (nxml-cdata-section-delimiter ((t (nil))))
     (nxml-char-ref-delimiter ((t (:foreground "#777"))))
     (nxml-char-ref-number ((t (:foreground "#777"))))
     (nxml-comment-content ((t (:foreground "grey"))))
     (nxml-comment-delimiter ((t (:bold t :weight bold :foreground "grey67"))))
     (nxml-delimited-data ((t (:foreground "#777"))))
     (nxml-delimiter ((t (nil))))
     (nxml-element-colon ((t (nil))))
     (nxml-element-local-name ((t (:foreground "grey72"))))
     (nxml-element-prefix ((t (:bold t :foreground "#777" :weight bold))))
     (nxml-entity-ref-delimiter ((t (:foreground "#777"))))
     (nxml-entity-ref-name ((t (:foreground "#777"))))
     (nxml-glyph ((t (:background "light grey" :foreground "black" :slant normal :weight normal))))
     (nxml-hash ((t (:bold t :foreground "#777" :weight bold))))
     (nxml-heading ((t (:bold t :weight bold))))
     (nxml-markup-declaration-delimiter ((t (nil))))
     (nxml-name ((t (:bold t :weight bold :foreground "#777"))))
     (nxml-namespace-attribute-colon ((t (nil))))
     (nxml-namespace-attribute-prefix ((t (:bold t :foreground "#888" :weight bold))))
     (nxml-namespace-attribute-value ((t (:foreground "#777"))))
     (nxml-namespace-attribute-value-delimiter ((t (:foreground "#777"))))
     (nxml-namespace-attribute-xmlns ((t (:bold t :weight bold :foreground "#777"))))
     (nxml-outline-active-indicator ((t (:bold t :stipple nil :background "#000" :foreground "#666" :inverse-video nil :strike-through nil :overline nil :underline nil :slant normal :weight bold :width normal :family "outline-consolas" :box 1 :height 83))))
     (nxml-outline-ellipsis ((t (:bold t :family "outline-consolas" :width normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#666" :background "#000" :stipple nil :weight bold :height 83))))
     (nxml-outline-indicator ((t (:bold t :family "outline-consolas" :width normal :weight bold :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#666" :background "#000" :stipple nil :height 83))))
     (nxml-processing-instruction-content ((t (:foreground "#777"))))
     (nxml-processing-instruction-delimiter ((t (nil))))
     (nxml-processing-instruction-target ((t (:foreground "#777"))))
     (nxml-prolog-keyword ((t (:foreground "#777"))))
     (nxml-prolog-literal-content ((t (:foreground "#777"))))
     (nxml-prolog-literal-delimiter ((t (:foreground "#777"))))
     (nxml-ref ((t (:foreground "#777"))))
     (nxml-tag-delimiter ((t (:foreground "#777"))))
     (nxml-tag-slash ((t (nil))))
     (nxml-text ((t (nil))))
     (org-agenda-restriction-lock ((t (:background "skyblue4"))))
     (org-agenda-structure ((t (:foreground "LightSkyBlue"))))
     (org-archived ((t (:foreground "grey50"))))
     (org-code ((t (:foreground "grey70"))))
     (org-column ((t (:background "grey30" :height 83 :family "outline-consolas"))))
     (org-date ((t (:foreground "Cyan" :underline t))))
     (org-done ((t (:bold t :foreground "PaleGreen" :weight bold))))
     (org-drawer ((t (:foreground "LightSkyBlue"))))
     (org-ellipsis ((t (:foreground "LightGoldenrod" :underline t))))
     (org-formula ((t (:foreground "chocolate1"))))
     (org-headline-done ((t (:foreground "LightSalmon"))))
     (org-hide ((t (:foreground "black"))))
     (org-latex-and-export-specials ((t (:foreground "burlywood"))))
     (org-level-1 ((t (:foreground "SkyBlue"))))
     (org-level-2 ((t (:foreground "darkseagreen"))))
     (org-level-3 ((t (:foreground "aquamarine3"))))
     (org-level-4 ((t (:foreground "grey67"))))
     (org-level-5 ((t (:foreground "LightSlateGray"))))
     (org-level-6 ((t (:foreground "SlateGray3"))))
     (org-level-7 ((t (:foreground "LightSteelBlue"))))
     (org-level-8 ((t (:foreground "PaleTurquoise4"))))
     (org-link ((t (:foreground "Cyan" :underline t))))
     (org-property-value ((t (nil))))
     (org-scheduled-previously ((t (:foreground "chocolate1"))))
     (org-scheduled-today ((t (:foreground "PaleGreen"))))
     (org-sexp-date ((t (:foreground "Cyan"))))
     (org-special-keyword ((t (:foreground "LightSalmon"))))
     (org-table ((t (:foreground "LightSkyBlue"))))
     (org-tag ((t (:bold t :weight bold))))
     (org-target ((t (:underline t))))
     (org-time-grid ((t (:foreground "LightGoldenrod"))))
     (org-todo ((t (:bold t :foreground "Pink" :weight bold))))
     (org-upcoming-deadline ((t (:foreground "chocolate1"))))
     (org-verbatim ((t (:foreground "grey70" :underline t))))
     (org-warning ((t (:bold t :weight bold :foreground "#999"))))
     (outline-1 ((t (:foreground "SkyBlue"))))
     (outline-2 ((t (:foreground "darkseagreen"))))
     (outline-3 ((t (:foreground "aquamarine3"))))
     (outline-4 ((t (:foreground "grey67"))))
     (outline-5 ((t (:foreground "LightSlateGray"))))
     (outline-6 ((t (:foreground "SlateGray3"))))
     (outline-7 ((t (:foreground "LightSteelBlue"))))
     (outline-8 ((t (:foreground "PaleTurquoise4"))))
     (p4-depot-added-face ((t (:foreground "blue"))))
     (p4-depot-deleted-face ((t (:foreground "red"))))
     (p4-depot-unmapped-face ((t (:foreground "grey30"))))
     (p4-diff-change-face ((t (:foreground "dark green"))))
     (p4-diff-del-face ((t (:foreground "red"))))
     (p4-diff-file-face ((t (:background "gray90"))))
     (p4-diff-head-face ((t (:background "gray95"))))
     (p4-diff-ins-face ((t (:foreground "blue"))))
     (paren-blink-off ((t (:foreground "darkblue"))))
     (paren-face-match ((t (:background "turquoise" :foreground "black"))))
     (paren-face-mismatch ((t (:background "purple" :foreground "white"))))
     (paren-face-no-match ((t (:background "yellow" :foreground "black"))))
     (paren-match ((t (:background "yellow" :foreground "darkblue"))))
     (paren-mismatch ((t (:background "DeepPink" :foreground "yellow"))))
     (paren-mismatch-face ((t (:background "DeepPink"))))
     (paren-no-match-face ((t (:background "yellow"))))
     (pointer ((t (nil))))
     (primary-selection ((t (:background "blue"))))
     (pulse-highlight-face ((t (:background "#AAAA33"))))
     (pulse-highlight-start-face ((t (:background "#AAAA33"))))
     (qt-classes-face ((t (:foreground "Red"))))
     (query-replace ((t (:background "blue"))))
     (red ((t (:foreground "red"))))
     ;;(region ((t (:background "dark cyan" :foreground "cyan"))))
     (region ((t (:background "#4f6af1" :foreground "gray"))))
     (right-margin ((t (nil))))
     (scroll-bar ((t (nil))))
     (search-buffers-face ((t (:bold t :background "ForestGreen" :weight bold))))
     (search-buffers-header-face ((t (:bold t :background "ForestGreen" :weight bold))))
     (secondary-selection ((t (:background "Aquamarine" :foreground "SlateBlue"))))
     (semantic-decoration-on-private-members-face ((t (:background "#8fffff"))))
     (semantic-decoration-on-protected-members-face ((t (:background "#fffff8"))))
     (semantic-dirty-token-face ((t (:background "lightyellow"))))
     (semantic-highlight-edits-face ((t (:background "gray90"))))
     (semantic-tag-boundary-face ((t (:italic t :slant italic))))
     (semantic-tag-highlight-face ((t (:background "#FFFFAA"))))
     (semantic-tag-highlight-start-face ((t (:background "#FFFFAA"))))
     (semantic-unmatched-syntax-face ((t (nil))))
     (senator-intangible-face ((t (:foreground "gray25"))))
     (senator-momentary-highlight-face ((t (:background "gray70"))))
     (senator-read-only-face ((t (:background "#CCBBBB"))))
     (setnu-line-number-face ((t (nil))))
     (sgml-namespace-face ((t (:foreground "LightSteelBlue"))))
     (sh-heredoc ((t (:foreground "yellow4"))))
     (shadow ((t (:foreground "grey50"))))
     (shell-option-face ((t (:background "darkblue" :foreground "cyan2"))))
     (shell-output-2-face ((t (:background "darkblue" :foreground "darkseagreen"))))
     (shell-output-3-face ((t (:background "darkblue" :foreground "lightgrey"))))
     (shell-output-face ((t (:background "darkblue" :foreground "white"))))
     (shell-prompt-face ((t (:foreground "#ECE7BA"))))
     (show-block-face1 ((t (:background "gray10"))))
     (show-block-face2 ((t (:background "gray15"))))
     (show-block-face3 ((t (:background "gray20"))))
     (show-block-face4 ((t (:background "gray25"))))
     (show-block-face5 ((t (:background "gray30"))))
     (show-block-face6 ((t (:background "gray35"))))
     (show-block-face7 ((t (:background "gray40"))))
     (show-block-face8 ((t (:background "gray45"))))
     (show-block-face9 ((t (:background "gray50"))))
     (show-paren-match-face ((t (:background "light slate blue" :foreground "white"))))
     (show-paren-mismatch-face ((t (:background "red" :foreground "white"))))
     (sldb-catch-tag-face ((t (nil))))
     (sldb-condition-face ((t (nil))))
     (sldb-detailed-frame-line-face ((t (nil))))
     (sldb-frame-label-face ((t (nil))))
     (sldb-frame-line-face ((t (nil))))
     (sldb-local-name-face ((t (nil))))
     (sldb-local-value-face ((t (nil))))
     (sldb-reference-face ((t (:underline t))))
     (sldb-restart-face ((t (nil))))
     (sldb-restart-number-face ((t (:bold t :weight bold))))
     (sldb-restart-type-face ((t (:foreground "aquamarine3"))))
     (sldb-section-face ((t (nil))))
     (sldb-topline-face ((t (nil))))
     (slime-error-face ((t (:underline "red"))))
     (slime-highlight-edits-face ((t (:background "lightgray"))))
     (slime-highlight-face ((t (:background "darkolivegreen" :underline nil))))
     (slime-inspector-action-face ((t (:bold t :foreground "RosyBrown" :weight bold))))
     (slime-inspector-label-face ((t (:foreground "SlateGray3"))))
     (slime-inspector-topline-face ((t (nil))))
     (slime-inspector-type-face ((t (:foreground "LightSlateGray"))))
     (slime-inspector-value-face ((t (:foreground "LightSteelBlue"))))
     (slime-note-face ((t (:underline "brown4"))))
     (slime-reader-conditional-face ((t (:foreground "grey67"))))
     (slime-repl-input-face ((t (:bold t :weight bold))))
     (slime-repl-inputed-output-face ((t (:foreground "SkyBlue"))))
     (slime-repl-output-face ((t (:foreground "PaleTurquoise4"))))
     (slime-repl-output-mouseover-face ((t (:foreground "SkyBlue" :box (:line-width 1 :color "black" :style released-button)))))
     (slime-repl-prompt-face ((t (:foreground "aquamarine3"))))
     (slime-repl-result-face ((t (nil))))
     (slime-style-warning-face ((t (:underline "brown"))))
     (slime-warning-face ((t (:underline "orange"))))
     (speedbar-button-face ((t (:foreground "green4"))))
     (speedbar-directory-face ((t (:foreground "blue4"))))
     (speedbar-file-face ((t (:foreground "cyan4"))))
     (speedbar-highlight-face ((t (:background "green"))))
     (speedbar-selected-face ((t (:foreground "red" :underline t))))
     (speedbar-separator-face ((t (:background "blue" :foreground "white" :overline "gray"))))
     (speedbar-tag-face ((t (:foreground "brown"))))
     (sr-active-path-face ((t (:foreground "blue"))))
     (sr-passive-path-face ((t (nil))))
     (svn-status-directory-face ((t (:foreground "blue4"))))
     (svn-status-filename-face ((t (:foreground "chocolate"))))
     (svn-status-locked-face ((t (:bold t :foreground "Red" :weight bold))))
     (svn-status-marked-face ((t (:foreground "green3"))))
     (svn-status-marked-popup-face ((t (:foreground "green3"))))
     (svn-status-switched-face ((t (:foreground "CadetBlue"))))
     (svn-status-symlink-face ((t (:foreground "cornflower blue"))))
     (svn-status-update-available-face ((t (:foreground "magenta"))))
     (template-message-face ((t (:bold t :weight bold))))
     (tempo-x-auto-face ((t (:background "light gray"))))
     (tempo-x-editable-face ((t (:background "light cyan"))))
     (tempo-x-form-face ((t (:background "light gray"))))
     (term-black ((t (:foreground "black"))))
     (term-blackbg ((t (nil))))
     (term-blue ((t (:foreground "blue"))))
     (term-blue-bold-face ((t (:bold t :foreground "blue" :weight bold))))
     (term-blue-face ((t (:foreground "blue"))))
     (term-blue-inv-face ((t (:background "blue"))))
     (term-blue-ul-face ((t (:foreground "blue" :underline t))))
     (term-bluebg ((t (:background "blue"))))
     (term-bold ((t (:bold t :weight bold))))
     (term-cyan ((t (:foreground "cyan"))))
     (term-cyan-bold-face ((t (:bold t :foreground "cyan" :weight bold))))
     (term-cyan-face ((t (:foreground "cyan"))))
     (term-cyan-inv-face ((t (:background "cyan"))))
     (term-cyan-ul-face ((t (:foreground "cyan" :underline t))))
     (term-cyanbg ((t (:background "cyan"))))
     (term-default-bg ((t (nil))))
     (term-default-bg-inv ((t (nil))))
     (term-default-bold-face ((t (:bold t :weight bold))))
     (term-default-face ((t (nil))))
     (term-default-fg ((t (nil))))
     (term-default-fg-inv ((t (nil))))
     (term-default-inv-face ((t (:background "peachpuff" :foreground "black"))))
     (term-default-ul-face ((t (:underline t))))
     (term-green ((t (:foreground "green"))))
     (term-green-bold-face ((t (:bold t :foreground "green" :weight bold))))
     (term-green-face ((t (:foreground "green"))))
     (term-green-inv-face ((t (:background "green"))))
     (term-green-ul-face ((t (:foreground "green" :underline t))))
     (term-greenbg ((t (:background "green"))))
     (term-invisible ((t (nil))))
     (term-invisible-inv ((t (nil))))
     (term-magenta ((t (:foreground "magenta"))))
     (term-magenta-bold-face ((t (:bold t :foreground "magenta" :weight bold))))
     (term-magenta-face ((t (:foreground "magenta"))))
     (term-magenta-inv-face ((t (:background "magenta"))))
     (term-magenta-ul-face ((t (:foreground "magenta" :underline t))))
     (term-magentabg ((t (:background "magenta"))))
     (term-red ((t (:foreground "red"))))
     (term-red-bold-face ((t (:bold t :foreground "red" :weight bold))))
     (term-red-face ((t (:foreground "red"))))
     (term-red-inv-face ((t (:background "red"))))
     (term-red-ul-face ((t (:foreground "red" :underline t))))
     (term-redbg ((t (:background "red"))))
     (term-underline ((t (:underline t))))
     (term-white ((t (:foreground "white"))))
     (term-white-bold-face ((t (:bold t :foreground "white" :weight bold))))
     (term-white-face ((t (:foreground "white"))))
     (term-white-inv-face ((t (nil))))
     (term-white-ul-face ((t (:foreground "white" :underline t))))
     (term-whitebg ((t (:background "white"))))
     (term-yellow ((t (:foreground "yellow"))))
     (term-yellow-bold-face ((t (:bold t :foreground "yellow" :weight bold))))
     (term-yellow-face ((t (:foreground "yellow"))))
     (term-yellow-inv-face ((t (:background "yellow"))))
     (term-yellow-ul-face ((t (:foreground "yellow" :underline t))))
     (term-yellowbg ((t (:background "yellow"))))
     (text-cursor ((t (:background "Red3" :foreground "white"))))
     (tool-bar ((t (:background "#111" :foreground "#777"))))
     (tooltip ((t (:background "#333" :foreground "#777" :family "helv"))))
     (trailing-whitespace ((t (:background "red1"))))
     (underline ((t (:bold t :underline nil :weight bold))))
     (variable-pitch ((t (nil))))
     (vcursor ((t (:background "cyan" :foreground "blue" :underline t))))
     (vertical-border ((t (:foreground "dark gray"))))
     (vertical-divider ((t (:foreground "gray"))))
     ;;(vertical-border ((t (nil))))
     ;;(vertical-divider ((t (nil))))
     (vhdl-font-lock-attribute-face ((t (:foreground "Orchid"))))
     (vhdl-font-lock-directive-face ((t (:foreground "CadetBlue"))))
     (vhdl-font-lock-enumvalue-face ((t (:foreground "Gold4"))))
     (vhdl-font-lock-function-face ((t (:foreground "Orchid4"))))
     (vhdl-font-lock-prompt-face ((t (:bold t :foreground "Red" :weight bold))))
     (vhdl-font-lock-reserved-words-face ((t (:bold t :foreground "Orange" :weight bold))))
     (vhdl-font-lock-translate-off-face ((t (:background "LightGray"))))
     (vhdl-speedbar-architecture-face ((t (:foreground "Blue"))))
     (vhdl-speedbar-architecture-selected-face ((t (:foreground "Blue" :underline t))))
     (vhdl-speedbar-configuration-face ((t (:foreground "DarkGoldenrod"))))
     (vhdl-speedbar-configuration-selected-face ((t (:foreground "DarkGoldenrod" :underline t))))
     (vhdl-speedbar-entity-face ((t (:foreground "ForestGreen"))))
     (vhdl-speedbar-entity-selected-face ((t (:foreground "ForestGreen" :underline t))))
     (vhdl-speedbar-instantiation-face ((t (:foreground "Brown"))))
     (vhdl-speedbar-instantiation-selected-face ((t (:foreground "Brown" :underline t))))
     (vhdl-speedbar-package-face ((t (:foreground "Grey50"))))
     (vhdl-speedbar-package-selected-face ((t (:foreground "Grey50" :underline t))))
     (viper-minibuffer-emacs ((t (:background "darkseagreen2" :foreground "Black"))))
     (viper-minibuffer-emacs-face ((t (:background "darkseagreen2" :foreground "Black"))))
     (viper-minibuffer-insert ((t (:background "pink" :foreground "Black"))))
     (viper-minibuffer-insert-face ((t (:background "pink" :foreground "Black"))))
     (viper-minibuffer-vi ((t (:background "grey" :foreground "DarkGreen"))))
     (viper-minibuffer-vi-face ((t (:background "grey" :foreground "DarkGreen"))))
     (viper-replace-overlay ((t (:background "darkseagreen2" :foreground "Black"))))
     (viper-replace-overlay-face ((t (:background "darkseagreen2" :foreground "Black"))))
     (viper-search ((t (:background "khaki" :foreground "Black"))))
     (viper-search-face ((t (:background "khaki" :foreground "Black"))))
     ;;(visible-mark-face ((t (:background "gray"))))
     (visible-mark-non-trailing-faces ((t (:foreground "grey80" :underline t))))
     (vvb-face ((t (:background "pink" :foreground "black"))))
     (which-func ((t (:foreground "LightSteelBlue"))))
     (white ((t (:foreground "white"))))
     (widget ((t (nil))))
     (widget-button ((t (:bold t :foreground "#888" :weight bold))))
     (widget-button-pressed ((t (:foreground "red"))))
     (widget-documentation ((t (:foreground "lime green"))))
     (widget-field ((t (:bold t :foreground "#999" :weight bold))))
     (widget-inactive ((t (:foreground "light gray"))))
     (widget-single-line-field ((t (:background "dim gray"))))
     (woman-addition-face ((t (:foreground "orange"))))
     (woman-bold-face ((t (:bold t :weight bold))))
     (woman-italic-face ((t (:foreground "beige"))))
     (woman-symbol-face ((t (nil))))
     (woman-unknown-face ((t (:foreground "LightSalmon"))))
     (x-face ((t (:bold t :background "wheat" :foreground "black" :weight bold))))
     (xrdb-option-name-face ((t (:bold t :foreground "yellow" :weight bold))))
     (xrdb-option-value-face ((t (:bold t :foreground "magenta" :weight bold))))
     (yellow ((t (:foreground "yellow"))))
     (js2-external-variable-face ((t (:foreground "#ECE7BA"))))
     (js2-jsdoc-html-tag-name-face ((t (:foreground "#ECE7BA"))))
     (zmacs-region ((t (:background "snow" :foreground "blue")))))))

(custom-set-variables
 '(ansi-color-names-vector (vector "grey" "sienna" "grey" "yellow" "DarkOliveGreen4" "DarkRed" "cornflowerblue" "white"))
 )

;; some nice colors here: http://ocanvas.org/
;; #66D9EF -- light blue


(add-to-list 'color-themes '(color-theme--dmb-late-night  "dmb late night" "david boon"))
