(defun my-color-theme ()
  "Color theme by u0103223, created 2008-05-08."
  (interactive)
  (color-theme-install
   '(my-color-theme
     ((background-color . "ivory")
      (background-mode . light)
      (border-color . "black")
      (cursor-color . "slateblue")
      (foreground-color . "black")
      (mouse-color . "slateblue"))
     ((list-matching-lines-buffer-name-face . underline)
      (list-matching-lines-face . bold)
      (widget-mouse-face . highlight))
     (default ((t (:stipple nil :background "ivory" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 83 :width normal :family "outline-consolas"))))
     (bold ((t (:bold t :weight bold))))
     (bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (border ((t (:background "black"))))
     (buffer-menu-buffer ((t (:bold t :weight bold))))
     (button ((t (:underline t))))
     (completions-common-part ((t (:family "outline-consolas" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "black" :background "ivory" :stipple nil :height 83))))
     (completions-first-difference ((t (:bold t :weight bold))))
     (cursor ((t (:background "slateblue" :foreground "black"))))
     (escape-glyph ((t (:foreground "brown"))))
     (file-name-shadow ((t (:foreground "grey50"))))
     (fixed-pitch ((t (:family "courier"))))
     (font-lock-builtin-face ((t (:foreground "black"))))
     (font-lock-comment-delimiter-face ((t (:italic t :slant italic :background "seashell"))))
     (font-lock-comment-face ((t (:italic t :background "seashell" :slant italic))))
     (font-lock-constant-face ((t (:foreground "darkblue"))))
     (font-lock-doc-face ((t (:background "lemonChiffon"))))
     (font-lock-function-name-face ((t (:bold t :underline t :weight bold))))
     (font-lock-keyword-face ((t (:foreground "blue"))))
     (font-lock-negation-char-face ((t (nil))))
     (font-lock-preprocessor-face ((t (:foreground "black"))))
     (font-lock-regexp-grouping-backslash ((t (:bold t :weight bold))))
     (font-lock-regexp-grouping-construct ((t (:bold t :weight bold))))
     (font-lock-string-face ((t (:background "lemonChiffon"))))
     (font-lock-type-face ((t (:foreground "black"))))
     (font-lock-variable-name-face ((t (:foreground "black"))))
     (font-lock-warning-face ((t (:bold t :foreground "Red" :weight bold))))
     (fringe ((t (:background "gray97"))))
     (header-line ((t (:bold t :background "grey90" :foreground "grey20" :box nil :underline t :weight bold))))
     (highlight ((t (:background "mistyRose" :foreground "black"))))
     (isearch ((t (:background "magenta4" :foreground "lightskyblue1"))))
     (isearch-fail ((t (:background "Plum" :foreground "Black"))))
     (italic ((t (:italic t :slant italic))))
     (lazy-highlight ((t (:background "paleturquoise"))))
     (link ((t (:foreground "blue1" :underline t))))
     (link-visited ((t (:underline t :foreground "magenta4"))))
     (match ((t (:background "yellow1"))))
     (menu ((t (nil))))
     (minibuffer-prompt ((t (:foreground "medium blue"))))
     (mode-line ((t (:bold t :background "mistyRose" :foreground "navy" :underline t :weight bold))))
     (mode-line-buffer-id ((t (:bold t :weight bold))))
     (mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
     (mode-line-inactive ((t (:underline t :background "grey90" :foreground "grey20" :box (:line-width -1 :color "grey75" :style nil) :weight light))))
     (mouse ((t (:background "slateblue"))))
     (next-error ((t (:foreground "black" :background "lavender"))))
     (nobreak-space ((t (:foreground "brown" :underline t))))
     (query-replace ((t (:foreground "lightskyblue1" :background "magenta4"))))
     (region ((t (:background "lavender" :foreground "black"))))
     (scroll-bar ((t (nil))))
     (secondary-selection ((t (:background "yellow"))))
     (shadow ((t (:foreground "grey50"))))
     (tool-bar ((t (:background "systembuttonface" :foreground "systembuttontext" :box (:line-width 1 :style released-button)))))
     (tooltip ((t (:family "helv" :background "systeminfowindow" :foreground "systeminfotext"))))
     (trailing-whitespace ((t (:background "red"))))
     (underline ((t (:underline t))))
     (variable-pitch ((t (:family "helv"))))
     (vertical-border ((t (nil))))
     (widget-button ((t (:bold t :weight bold))))
     (widget-button-pressed ((t (:foreground "red"))))
     (widget-documentation ((t (:foreground "dark green"))))
     (widget-field ((t (:background "gray85"))))
     (widget-inactive ((t (:foreground "dim gray"))))
     (widget-single-line-field ((t (:background "gray85")))))))