(eval-when-compile    (require 'color-theme))
(defun color-theme--dmb-domq ()
  "Color theme by David M. Boon, created 2008-02-26."
  (interactive)
  (color-theme-install
   '(color-theme--dmb-domq
     ((background-color . "white")
      (background-mode . light)
      (border-color . "black")
      (cursor-color . "black")
      (foreground-color . "black")
      (mouse-color . "black"))
     ((Man-overstrike-face . bold)
      (Man-reverse-face . highlight)
      (Man-underline-face . underline)
      (apropos-keybinding-face . underline)
      (apropos-label-face . italic)
      (apropos-match-face . match)
      (apropos-property-face . bold-italic)
      (apropos-symbol-face . bold)
      (compilation-message-face . underline)
      (highline-face . dmb-current-line-face)
      (highline-vertical-face . highline-vertical-face)
      (ibuffer-deletion-face . font-lock-type-face)
      (ibuffer-filter-group-name-face . bold)
      (ibuffer-marked-face . font-lock-warning-face)
      (ibuffer-title-face . font-lock-type-face)
      (list-matching-lines-buffer-name-face . underline)
      (list-matching-lines-face . match)
      (moccur-maximum-displayed-with-color . 500)
      (paren-match-face . paren-face-match)
      (paren-mismatch-face . paren-face-mismatch)
      (paren-no-match-face . paren-face-no-match)
      (ps-line-number-color . "black")
      (ps-zebra-color . 0.95)
      (tags-tag-face . default)
      (vc-annotate-very-old-color . "#3F3FFF")
      (view-highlight-face . highlight)
      (widget-mouse-face . highlight))
     (default ((t (:bold t :stipple nil :background "white" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight bold :height 83 :width normal :family "outline-consolas"))))
     (anything-header ((t (nil))))
     (anything-isearch-match ((t (:background "Yellow"))))
     (bold ((t (:bold t :weight bold))))
     (bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (border ((t (:background "black"))))
     (buffer-menu-buffer ((t (:bold t :weight bold))))
     (buffer-menu-buffer-name ((t (:foreground "Blue"))))
     (buffer-menu-current-buffer ((t (:background "Aquamarine" :foreground "Red"))))
     (buffer-menu-delete-mark ((t (:background "Red" :foreground "Aquamarine"))))
     (buffer-menu-directory-buffer ((t (:background "LightBlue" :foreground "Blue"))))
     (buffer-menu-file-name ((t (:foreground "DarkMagenta"))))
     (buffer-menu-flagged-buffer ((t (:foreground "Red"))))
     (buffer-menu-headings ((t (:background "DarkGreen" :foreground "Orange"))))
     (buffer-menu-marked-buffer ((t (:underline t))))
     (buffer-menu-mode ((t (:foreground "DarkGreen"))))
     (buffer-menu-modified-mark ((t (:foreground "DarkOrange"))))
     (buffer-menu-read-only-mark ((t (:foreground "Yellow"))))
     (buffer-menu-save-mark ((t (:background "Blue" :foreground "Orange"))))
     (buffer-menu-size ((t (:foreground "DarkRed"))))
     (buffer-menu-star-buffer ((t (:foreground "DarkBlue"))))
     (buffer-menu-time ((t (:foreground "DarkGoldenrod4"))))
     (buffer-menu-view-mark ((t (:background "Aquamarine" :foreground "Red"))))
     (button ((t (:underline t))))
     (change-log-acknowledgement ((t (:foreground "#9b1d1d"))))
     (change-log-conditionals ((t (:foreground "#a07409"))))
     (change-log-date ((t (:foreground "#a47c7c"))))
     (change-log-email ((t (:foreground "#a07409"))))
     (change-log-file ((t (:foreground "#0000de"))))
     (change-log-function ((t (:foreground "#a07409"))))
     (change-log-list ((t (:foreground "#8b1bd1"))))
     (change-log-name ((t (:foreground "#52898b"))))
     (comint-highlight-input ((t (:bold t :weight bold))))
     (comint-highlight-prompt ((t (:foreground "dark blue"))))
     (compilation-column-number ((t (:foreground "cyan3"))))
     (compilation-error ((t (:bold t :foreground "Red1" :weight bold))))
     (compilation-info ((t (:bold t :foreground "Green3" :weight bold))))
     (compilation-line-number ((t (:foreground "darkgoldenrod" :underline nil))))
     (compilation-warning ((t (:bold t :foreground "Orange" :weight bold))))
     (completions-common-part ((t (:background "white" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 120 :width normal))))
     (completions-first-difference ((t (:bold t :weight bold))))
     (cursor ((t (:background "black"))))
     (custom-button ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style released-button)))))
     (custom-button-mouse ((t (:background "grey90" :foreground "black" :box (:line-width 2 :style released-button)))))
     (custom-button-pressed ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style pressed-button)))))
     (custom-button-pressed-unraised ((t (:underline t :foreground "magenta4"))))
     (custom-button-unraised ((t (:underline t))))
     (custom-changed ((t (:background "blue1" :foreground "white"))))
     (custom-comment ((t (:background "gray85"))))
     (custom-comment-tag ((t (:foreground "blue4"))))
     (custom-documentation ((t (nil))))
     (custom-face-tag ((t (:bold t :family "helv" :weight bold :height 1.2))))
     (custom-group-tag ((t (:bold t :family "helv" :foreground "blue1" :weight bold :height 1.2))))
     (custom-group-tag-1 ((t (:bold t :family "helv" :foreground "red1" :weight bold :height 1.2))))
     (custom-invalid ((t (:background "red1" :foreground "yellow1"))))
     (custom-link ((t (:underline t :foreground "blue1"))))
     (custom-modified ((t (:background "blue1" :foreground "white"))))
     (custom-rogue ((t (:background "black" :foreground "pink"))))
     (custom-saved ((t (:underline t))))
     (custom-set ((t (:background "white" :foreground "blue1"))))
     (custom-state ((t (:foreground "dark green"))))
     (custom-themed ((t (:background "blue1" :foreground "white"))))
     (custom-variable-button ((t (:bold t :underline t :weight bold))))
     (custom-variable-tag ((t (:bold t :foreground "blue1" :weight bold))))
     (custom-visibility ((t (:underline t :foreground "blue1" :height 0.8))))
     (diff-added ((t (nil))))
     (diff-changed ((t (nil))))
     (diff-context ((t (:foreground "grey50"))))
     (diff-file-header ((t (:bold t :background "grey70" :weight bold))))
     (diff-function ((t (:background "grey85"))))
     (diff-header ((t (:background "grey85"))))
     (diff-hunk-header ((t (:background "grey85"))))
     (diff-index ((t (:bold t :weight bold :background "grey70"))))
     (diff-indicator-added ((t (nil))))
     (diff-indicator-changed ((t (nil))))
     (diff-indicator-removed ((t (nil))))
     (diff-nonexistent ((t (:bold t :weight bold :background "grey70"))))
     (diff-refine-change ((t (:background "grey90"))))
     (diff-removed ((t (nil))))
     (dired-directory ((t (:foreground "#0000de"))))
     (dired-flagged ((t (:bold t :weight bold :foreground "Red1"))))
     (dired-header ((t (:foreground "#1d791d"))))
     (dired-ignored ((t (:foreground "grey50"))))
     (dired-mark ((t (:foreground "#52898b"))))
     (dired-marked ((t (:bold t :weight bold :foreground "Red1"))))
     (dired-symlink ((t (:foreground "#8b1bd1"))))
     (dired-warn-writable ((t (:bold t :family "outline-consolas" :width normal :weight bold :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "black" :background "white" :stipple nil :height 83))))
     (dired-warning ((t (:bold t :weight bold :foreground "Red1"))))
     (dmb-blink-region-face ((t (:background "lavendar"))))
     (dmb-current-line-face ((t (:background "alice blue"))))
     (dmb-face-five ((t (:foreground "IndianRed"))))
     (dmb-face-four ((t (:foreground "#997009"))))
     (dmb-face-hi-light-line-error ((t (:foreground "maroon"))))
     (dmb-face-ibuffer-elisp ((t (:foreground "SeaGreen"))))
     (dmb-face-ibuffer-jde ((t (:foreground "MediumAquamarine"))))
     (dmb-face-light-blue ((t (:foreground "LightSkyBlue"))))
     (dmb-face-one ((t (:foreground "midnight blue"))))
     (dmb-face-onex ((t (:foreground "LightSkyBlue"))))
     (dmb-face-six ((t (:foreground "DarkSlateBlue"))))
     (dmb-face-three ((t (:foreground "DarkOrange"))))
     (dmb-face-two ((t (:foreground "medium sea green"))))
     (dmb-grep-hit-face ((t (:foreground "DarkSlateBlue" :underline nil))))
     (dmb-grep-match-face ((t (:foreground "DarkSlateBlue" :underline nil))))
     (dmb-mark-face ((t (:foreground "cyan" :underline nil))))
     (dmb-notes-txt-face ((t (:foreground "DodgerBlue" :underline nil))))
     (ediff-current-diff-A ((t (:background "pale green" :foreground "firebrick"))))
     (ediff-current-diff-Ancestor ((t (:background "VioletRed" :foreground "Black"))))
     (ediff-current-diff-B ((t (:background "Yellow" :foreground "DarkOrchid"))))
     (ediff-current-diff-C ((t (:background "Pink" :foreground "Navy"))))
     (ediff-even-diff-A ((t (:background "light grey" :foreground "Black"))))
     (ediff-even-diff-Ancestor ((t (:background "Grey" :foreground "White"))))
     (ediff-even-diff-B ((t (:background "Grey" :foreground "White"))))
     (ediff-even-diff-C ((t (:background "light grey" :foreground "Black"))))
     (ediff-fine-diff-A ((t (:background "sky blue" :foreground "Navy"))))
     (ediff-fine-diff-Ancestor ((t (:background "Green" :foreground "Black"))))
     (ediff-fine-diff-B ((t (:background "cyan" :foreground "Black"))))
     (ediff-fine-diff-C ((t (:background "Turquoise" :foreground "Black"))))
     (ediff-odd-diff-A ((t (:background "Grey" :foreground "White"))))
     (ediff-odd-diff-Ancestor ((t (:background "gray40" :foreground "cyan3"))))
     (ediff-odd-diff-B ((t (:background "light grey" :foreground "Black"))))
     (ediff-odd-diff-C ((t (:background "Grey" :foreground "White"))))
     (eieio-custom-slot-tag-face ((t (:foreground "blue"))))
     (eldoc-highlight-function-argument ((t (:bold t :weight bold))))
     (escape-glyph ((t (:foreground "brown"))))
     (ffap ((t (:background "darkseagreen2"))))
     (file-name-shadow ((t (:foreground "grey50"))))
     (fixed-pitch ((t (:family "courier"))))
     (flymake-errline ((t (:underline "OrangeRed"))))
     (flymake-warnline ((t (:underline "DarkSlateBlue"))))
     (font-lock-builtin-face ((t (:foreground "#be61ba"))))
     (font-lock-comment-delimiter-face ((t (:foreground "blue4"))))
     (font-lock-comment-face ((t (:foreground "#9b1d1d"))))
     (font-lock-constant-face ((t (:foreground "#52898b"))))
     (font-lock-doc-face ((t (:foreground "green4"))))
     (font-lock-function-name-face ((t (:foreground "#0000de"))))
     (font-lock-keyword-face ((t (:foreground "#8b1bd1"))))
     (font-lock-negation-char-face ((t (nil))))
     (font-lock-preprocessor-face ((t (:foreground "Orchid"))))
     (font-lock-regexp-grouping-backslash ((t (:bold t :weight bold))))
     (font-lock-regexp-grouping-construct ((t (:bold t :weight bold))))
     (font-lock-string-face ((t (:foreground "#a47c7c"))))
     (font-lock-type-face ((t (:foreground "#1d791d"))))
     (font-lock-variable-name-face ((t (:foreground "#a07409"))))
     (font-lock-warning-face ((t (:bold t :foreground "Red1" :weight bold))))
     (fringe ((t (:background "gray97"))))
     (header-line ((t (:background "grey90" :foreground "grey20" :box nil))))
     (help-argument-name ((t (:italic t :slant italic))))
     (hi-black-b ((t (:bold t :weight bold))))
     (hi-black-hb ((t (:bold t :family "helv" :weight bold :height 1.67))))
     (hi-blue ((t (:background "light blue"))))
     (hi-blue-b ((t (:bold t :foreground "blue1" :weight bold))))
     (hi-green ((t (:foreground "PaleGreen2"))))
     (hi-green-b ((t (:bold t :foreground "green1" :weight bold))))
     (hi-indian-red ((t (:background "IndianRed1"))))
     (hi-indian-red-fg ((t (:foreground "IndianRed1"))))
     (hi-lemon-chiffon ((t (:background "lemon chiffon"))))
     (hi-light-goldenrod ((t (:background "light goldenrod"))))
     (hi-pink ((t (:background "pink"))))
     (hi-red-b ((t (:bold t :foreground "red1" :weight bold))))
     (hi-yellow ((t (:background "yellow1"))))
     (highlight ((t (:background "darkseagreen2"))))
     (highline-face ((t (:background "darkseagreen2"))))
     (highline-vertical-face ((t (:background "yellow1"))))
     (ibuffer-deletion-face ((t (:foreground "red"))))
     (ibuffer-marked-face ((t (:foreground "green"))))
     (ido-first-match ((t (:bold t :weight bold))))
     (ido-incomplete-regexp ((t (:bold t :weight bold :foreground "Red1"))))
     (ido-indicator ((t (:background "red1" :foreground "yellow1" :width condensed))))
     (ido-only-match ((t (:foreground "ForestGreen"))))
     (ido-subdir ((t (:foreground "red1"))))
     (info-header-node ((t (:italic t :bold t :weight bold :slant italic :foreground "brown"))))
     (info-header-xref ((t (:foreground "blue1" :underline t))))
     (info-menu-header ((t (:bold t :family "helv" :weight bold))))
     (info-menu-star ((t (:foreground "red1"))))
     (info-node ((t (:italic t :bold t :foreground "brown" :slant italic :weight bold))))
     (info-title-1 ((t (:bold t :weight bold :family "helv" :height 1.728))))
     (info-title-2 ((t (:bold t :family "helv" :weight bold :height 1.44))))
     (info-title-3 ((t (:bold t :weight bold :family "helv" :height 1.2))))
     (info-title-4 ((t (:bold t :family "helv" :weight bold))))
     (info-xref ((t (:underline t :foreground "blue1"))))
     (info-xref-visited ((t (:underline t :foreground "magenta4"))))
     (isearch ((t (:background "magenta4" :foreground "lightskyblue1"))))
     (isearch-fail ((t (:background "Plum" :foreground "Black"))))
     (iswitchb-current-match ((t (:foreground "#0000de"))))
     (iswitchb-invalid-regexp ((t (:bold t :weight bold :foreground "Red1"))))
     (iswitchb-single-match ((t (:foreground "#9b1d1d"))))
     (iswitchb-virtual-matches ((t (:foreground "#be61ba"))))
     (italic ((t (:italic t :slant italic))))
     (jabber-activity-face ((t (:bold t :foreground "red" :weight bold))))
     (jabber-chat-error ((t (:bold t :foreground "red" :weight bold))))
     (jabber-chat-prompt-foreign ((t (:bold t :foreground "red" :weight bold))))
     (jabber-chat-prompt-local ((t (:bold t :foreground "blue" :weight bold))))
     (jabber-chat-prompt-system ((t (:bold t :foreground "green" :weight bold))))
     (jabber-chat-text-foreign ((t (nil))))
     (jabber-chat-text-local ((t (nil))))
     (jabber-rare-time-face ((t (:foreground "darkgreen" :underline t))))
     (jabber-roster-user-away ((t (:italic t :foreground "dark green" :slant italic :weight normal))))
     (jabber-roster-user-chatty ((t (:bold t :foreground "dark orange" :slant normal :weight bold))))
     (jabber-roster-user-dnd ((t (:italic t :foreground "red" :slant italic :weight normal))))
     (jabber-roster-user-error ((t (:italic t :foreground "red" :slant italic :weight light))))
     (jabber-roster-user-offline ((t (:italic t :foreground "dark grey" :slant italic :weight light))))
     (jabber-roster-user-online ((t (:bold t :foreground "blue" :slant normal :weight bold))))
     (jabber-roster-user-xa ((t (:italic t :foreground "black" :slant italic :weight normal))))
     (jabber-title-large ((t (:bold t :family "helv" :weight bold :height 3.0 :width ultra-expanded))))
     (jabber-title-medium ((t (:bold t :family "helv" :weight bold :height 2.0 :width expanded))))
     (jabber-title-small ((t (:bold t :family "helv" :weight bold :height 1.0 :width semi-expanded))))
     (jde-bug-breakpoint-cursor ((t (:background "brown" :foreground "cyan"))))
     (jde-db-active-breakpoint-face ((t (:background "red" :foreground "black"))))
     (jde-db-requested-breakpoint-face ((t (:background "yellow" :foreground "black"))))
     (jde-db-spec-breakpoint-face ((t (:background "green" :foreground "black"))))
     (jde-java-font-lock-api-face ((t (:foreground "dark goldenrod"))))
     (jde-java-font-lock-bold-face ((t (:bold t :weight bold))))
     (jde-java-font-lock-code-face ((t (nil))))
     (jde-java-font-lock-constant-face ((t (:foreground "CadetBlue"))))
     (jde-java-font-lock-doc-tag-face ((t (:foreground "green4"))))
     (jde-java-font-lock-italic-face ((t (:italic t :slant italic))))
     (jde-java-font-lock-link-face ((t (:foreground "blue" :underline t :slant normal))))
     (jde-java-font-lock-modifier-face ((t (:foreground "Orchid"))))
     (jde-java-font-lock-number-face ((t (:foreground "RosyBrown"))))
     (jde-java-font-lock-operator-face ((t (:foreground "medium blue"))))
     (jde-java-font-lock-package-face ((t (:foreground "blue3"))))
     (jde-java-font-lock-pre-face ((t (nil))))
     (jde-java-font-lock-private-face ((t (:foreground "Orchid"))))
     (jde-java-font-lock-protected-face ((t (:foreground "Orchid"))))
     (jde-java-font-lock-public-face ((t (:foreground "Orchid"))))
     (jde-java-font-lock-underline-face ((t (:underline t))))
     (lazy-highlight ((t (:background "paleturquoise"))))
     (link ((t (:foreground "blue1" :underline t))))
     (link-visited ((t (:foreground "magenta4" :underline t))))
     (mac-ts-block-fill-text ((t (:underline t))))
     (mac-ts-caret-position ((t (nil))))
     (mac-ts-converted-text ((t (:underline "gray80"))))
     (mac-ts-no-hilite ((t (:background "white" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 120 :width normal))))
     (mac-ts-outline-text ((t (:underline t))))
     (mac-ts-raw-text ((t (:underline t))))
     (mac-ts-selected-converted-text ((t (:underline t))))
     (mac-ts-selected-raw-text ((t (:underline t))))
     (mac-ts-selected-text ((t (:underline t))))
     (match ((t (:background "yellow1"))))
     (menu ((t (nil))))
     (minibuffer-prompt ((t (:foreground "medium blue"))))
     (mmm-cleanup-submode-face ((t (:background "Wheat"))))
     (mmm-code-submode-face ((t (:background "LightGray"))))
     (mmm-comment-submode-face ((t (:background "SkyBlue"))))
     (mmm-declaration-submode-face ((t (:background "Aquamarine"))))
     (mmm-default-submode-face ((t (:background "gray85"))))
     (mmm-delimiter-face ((t (nil))))
     (mmm-init-submode-face ((t (:background "Pink"))))
     (mmm-output-submode-face ((t (:background "Plum"))))
     (mmm-special-submode-face ((t (:background "MediumSpringGreen"))))
     (moccur-current-line-face ((t (:underline t))))
     (moccur-face ((t (:bold t :background "light cyan" :weight bold))))
     ;;(mode-line ((t (:background "grey75" :foreground "black" :box (:line-width -1 :style released-button)))))
     (mode-line ((t (:background "grey90" :foreground "black" :box (:line-width -1 :color "grey75") :width normal)))) 
     (mode-line-inactive ((t (:background "grey90" :foreground "grey" :box (:line-width -1 :color "grey75" :style nil) ))))
     (mode-line-buffer-id ((t (:bold t :weight bold))))
     (mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
     (mouse ((t (:background "black"))))
     (mumamo-background-chunk-major ((t (:background "cornsilk"))))
     (mumamo-background-chunk-submode ((t (:background "azure"))))
     (next-error ((t (:background "lightgoldenrod2"))))
     (nobreak-space ((t (:foreground "brown" :underline t))))
     (nxml-attribute-colon ((t (nil))))
     (nxml-attribute-local-name ((t (:foreground "#a07409"))))
     (nxml-attribute-prefix ((t (:foreground "#be61ba"))))
     (nxml-attribute-value ((t (:foreground "#a47c7c"))))
     (nxml-attribute-value-delimiter ((t (:foreground "#a47c7c"))))
     (nxml-cdata-section-CDATA ((t (:foreground "#be61ba"))))
     (nxml-cdata-section-content ((t (nil))))
     (nxml-cdata-section-delimiter ((t (nil))))
     (nxml-char-ref-delimiter ((t (:foreground "#52898b"))))
     (nxml-char-ref-number ((t (:foreground "#52898b"))))
     (nxml-comment-content ((t (:foreground "#9b1d1d"))))
     (nxml-comment-delimiter ((t (:foreground "blue4"))))
     (nxml-delimited-data ((t (:foreground "green4"))))
     (nxml-delimiter ((t (nil))))
     (nxml-element-colon ((t (nil))))
     (nxml-element-local-name ((t (:foreground "#0000de"))))
     (nxml-element-prefix ((t (:foreground "#be61ba"))))
     (nxml-entity-ref-delimiter ((t (:foreground "#52898b"))))
     (nxml-entity-ref-name ((t (:foreground "#52898b"))))
     (nxml-glyph ((t (:background "light grey" :foreground "black" :slant normal :weight normal))))
     (nxml-hash ((t (:foreground "#be61ba"))))
     (nxml-heading ((t (:bold t :weight bold))))
     (nxml-markup-declaration-delimiter ((t (nil))))
     (nxml-name ((t (:foreground "#be61ba"))))
     (nxml-namespace-attribute-colon ((t (nil))))
     (nxml-namespace-attribute-prefix ((t (:foreground "#a07409"))))
     (nxml-namespace-attribute-value ((t (:foreground "#a47c7c"))))
     (nxml-namespace-attribute-value-delimiter ((t (:foreground "#a47c7c"))))
     (nxml-namespace-attribute-xmlns ((t (:foreground "#be61ba"))))
     (nxml-outline-active-indicator ((t (:bold t :stipple nil :background "white" :foreground "black" :inverse-video nil :strike-through nil :overline nil :underline nil :slant normal :weight bold :width normal :family "outline-consolas" :box 1 :height 83))))
     (nxml-outline-ellipsis ((t (:bold t :family "outline-consolas" :width normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "black" :background "white" :stipple nil :weight bold :height 83))))
     (nxml-outline-indicator ((t (:bold t :family "outline-consolas" :width normal :weight bold :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "black" :background "white" :stipple nil :height 83))))
     (nxml-processing-instruction-content ((t (:foreground "green4"))))
     (nxml-processing-instruction-delimiter ((t (nil))))
     (nxml-processing-instruction-target ((t (:foreground "#8b1bd1"))))
     (nxml-prolog-keyword ((t (:foreground "#8b1bd1"))))
     (nxml-prolog-literal-content ((t (:foreground "green4"))))
     (nxml-prolog-literal-delimiter ((t (:foreground "green4"))))
     (nxml-ref ((t (:foreground "#52898b"))))
     (nxml-tag-delimiter ((t (nil))))
     (nxml-tag-slash ((t (nil))))
     (nxml-text ((t (nil))))
     (outline-1 ((t (:foreground "#0000de"))))
     (outline-2 ((t (:foreground "#a07409"))))
     (outline-3 ((t (:foreground "#8b1bd1"))))
     (outline-4 ((t (:foreground "#9b1d1d"))))
     (outline-5 ((t (:foreground "#1d791d"))))
     (outline-6 ((t (:foreground "#52898b"))))
     (outline-7 ((t (:foreground "#be61ba"))))
     (outline-8 ((t (:foreground "#a47c7c"))))
     (paren-face-match ((t (:background "turquoise"))))
     (paren-face-mismatch ((t (:background "purple" :foreground "white"))))
     (paren-face-no-match ((t (:background "yellow" :foreground "black"))))
     (query-replace ((t (:background "magenta4" :foreground "lightskyblue1"))))
     (region ((t (:background "lightgoldenrod2"))))
     (rst-level-1-face ((t (:background "grey85"))))
     (rst-level-2-face ((t (:background "grey78"))))
     (rst-level-3-face ((t (:background "grey71"))))
     (rst-level-4-face ((t (:background "grey64"))))
     (rst-level-5-face ((t (:background "grey57"))))
     (rst-level-6-face ((t (:background "grey50"))))
     (scroll-bar ((t (nil))))
     (search-buffers-face ((t (:bold t :background "ForestGreen" :weight bold))))
     (search-buffers-header-face ((t (:bold t :background "ForestGreen" :weight bold))))
     (secondary-selection ((t (:background "yellow1"))))
     (semantic-highlight-edits-face ((t (:background "gray90"))))
     (semantic-tag-highlight-face ((t (:background "#FFFFAA"))))
     (semantic-tag-highlight-start-face ((t (:background "#FFFFAA"))))
     (semantic-unmatched-syntax-face ((t (:underline "red"))))
     (senator-intangible-face ((t (:foreground "gray25"))))
     (senator-momentary-highlight-face ((t (:background "gray70"))))
     (senator-read-only-face ((t (:background "#CCBBBB"))))
     (sgml-namespace-face ((t (:foreground "#be61ba"))))
     (shadow ((t (:foreground "grey50"))))
     (sldb-catch-tag-face ((t (nil))))
     (sldb-condition-face ((t (nil))))
     (sldb-detailed-frame-line-face ((t (nil))))
     (sldb-frame-label-face ((t (nil))))
     (sldb-frame-line-face ((t (nil))))
     (sldb-local-name-face ((t (nil))))
     (sldb-local-value-face ((t (nil))))
     (sldb-reference-face ((t (:underline t))))
     (sldb-restart-face ((t (nil))))
     (sldb-restart-number-face ((t (:bold t :weight bold))))
     (sldb-restart-type-face ((t (:foreground "#8b1bd1"))))
     (sldb-section-face ((t (nil))))
     (sldb-topline-face ((t (nil))))
     (slime-error-face ((t (:underline "red"))))
     (slime-highlight-edits-face ((t (:background "lightgray"))))
     (slime-highlight-face ((t (:background "darkseagreen2" :underline nil))))
     (slime-inspector-action-face ((t (:bold t :weight bold :foreground "Red1"))))
     (slime-inspector-label-face ((t (:foreground "#52898b"))))
     (slime-inspector-topline-face ((t (nil))))
     (slime-inspector-type-face ((t (:foreground "#1d791d"))))
     (slime-inspector-value-face ((t (:foreground "#be61ba"))))
     (slime-note-face ((t (:underline "brown4"))))
     (slime-reader-conditional-face ((t (:foreground "#9b1d1d"))))
     (slime-repl-input-face ((t (:bold t :weight bold))))
     (slime-repl-inputed-output-face ((t (:foreground "Red"))))
     (slime-repl-output-face ((t (:foreground "#a47c7c"))))
     (slime-repl-output-mouseover-face ((t (:foreground "Red" :box (:line-width 1 :color "black" :style released-button)))))
     (slime-repl-prompt-face ((t (:foreground "#8b1bd1"))))
     (slime-repl-result-face ((t (nil))))
     (slime-style-warning-face ((t (:underline "brown"))))
     (slime-warning-face ((t (:underline "orange"))))
     (speedbar-button-face ((t (:foreground "green4"))))
     (speedbar-directory-face ((t (:foreground "blue4"))))
     (speedbar-file-face ((t (:foreground "cyan4"))))
     (speedbar-highlight-face ((t (:background "green"))))
     (speedbar-selected-face ((t (:foreground "red" :underline t))))
     (speedbar-separator-face ((t (:background "blue" :foreground "white" :overline "gray"))))
     (speedbar-tag-face ((t (:foreground "brown"))))
     (svn-status-directory-face ((t (:foreground "blue4"))))
     (svn-status-filename-face ((t (:foreground "chocolate"))))
     (svn-status-locked-face ((t (:bold t :foreground "Red" :weight bold))))
     (svn-status-marked-face ((t (:foreground "green3"))))
     (svn-status-marked-popup-face ((t (:foreground "green3"))))
     (svn-status-switched-face ((t (:foreground "CadetBlue"))))
     (svn-status-symlink-face ((t (:foreground "cornflower blue"))))
     (svn-status-update-available-face ((t (:foreground "magenta"))))
     (tempo-x-auto-face ((t (:background "light gray"))))
     (tempo-x-editable-face ((t (:background "light cyan"))))
     (tempo-x-form-face ((t (:background "light gray"))))
     (tool-bar ((t (:background "systembuttonface" :foreground "systembuttontext" :box (:line-width 1 :style released-button)))))
     (tooltip ((t (:background "systeminfowindow" :foreground "systeminfotext" :family "helv"))))
     (trailing-whitespace ((t (:background "red"))))
     (underline ((t (:underline t))))
     (variable-pitch ((t (:family "helv"))))
     (vertical-border ((t (nil))))
     (which-func ((t (:foreground "#0000de"))))
     (whitespace-empty ((t (:background "yellow" :foreground "firebrick"))))
     (whitespace-hspace ((t (:background "LemonChiffon3" :foreground "aquamarine3"))))
     (whitespace-indentation ((t (:background "yellow" :foreground "firebrick"))))
     (whitespace-line ((t (:background "gray20" :foreground "violet"))))
     (whitespace-newline ((t (:bold t :background "linen" :foreground "aquamarine3" :weight bold))))
     (whitespace-space ((t (:background "LightYellow" :foreground "aquamarine3"))))
     (whitespace-space-after-tab ((t (:background "yellow" :foreground "firebrick"))))
     (whitespace-space-before-tab ((t (:background "DarkOrange" :foreground "firebrick"))))
     (whitespace-tab ((t (:background "beige" :foreground "aquamarine3"))))
     (whitespace-trailing ((t (:bold t :background "red1" :foreground "yellow" :weight bold))))
     (widget-button ((t (:bold t :weight bold))))
     (widget-button-pressed ((t (:foreground "red1"))))
     (widget-documentation ((t (:foreground "dark green"))))
     (widget-field ((t (:background "gray85"))))
     (widget-inactive ((t (:foreground "grey50"))))
     (widget-single-line-field ((t (:background "gray85"))))
     (woman-addition-face ((t (:foreground "orange"))))
     (woman-bold-face ((t (:bold t :foreground "blue" :weight bold))))
     (woman-italic-face ((t (:italic t :foreground "red" :underline t :slant italic))))
     (woman-symbol-face ((t (nil))))
     (woman-unknown-face ((t (:foreground "brown")))))))
(add-to-list 'color-themes '(color-theme--dmb-domq "color-theme--dmb-domq" "david boon"))