;;(add-to-list 'load-path (*emacs ".emacs.x/.emacs.p/jdee.trunk/jde/dist/lisp"))
(add-to-list 'load-path "f:/devtools/emacs-eclim")
(load-library "eclim")
(setq eclim-auto-save t)
(global-eclim-mode)
