(require 'color-theme)

(eval-when-compile (require 'color-theme))
(defun color-theme--dmb-arjen2 ()
  "Color theme by David M. Boon, created 2008-01-08."
  (interactive)
  (color-theme-install
   '(color-theme--dmb-arjen2
     ((background-color . "black")
      (background-mode . dark)
      (border-color . "black")
      (cursor-color . "yellow")
      (foreground-color . "grey74")
      (mouse-color . "sienna1"))
     ((Man-overstrike-face . bold)
      (Man-reverse-face . highlight)
      (Man-underline-face . underline)
      (apropos-keybinding-face . underline)
      (apropos-label-face . italic)
      (apropos-match-face . match)
      (apropos-property-face . bold-italic)
      (apropos-symbol-face . bold)
      (compilation-message-face . underline)
      (ecb-directories-general-face . ecb-default-general-face)
      (ecb-directory-face . ecb-default-highlight-face)
      (ecb-directory-not-accessible-face . ecb-directory-not-accessible-face)
      (ecb-history-face . ecb-default-highlight-face)
      (ecb-history-general-face . ecb-default-general-face)
      (ecb-method-face . ecb-default-highlight-face)
      (ecb-method-non-semantic-face . speedbar-tag-face)
      (ecb-methods-general-face . ecb-default-general-face)
      (ecb-mode-line-data-face . ecb-mode-line-data-face)
      (ecb-mode-line-prefix-face . ecb-mode-line-prefix-face)
      (ecb-mode-line-win-nr-face . ecb-mode-line-win-nr-face)
      (ecb-source-face . ecb-default-highlight-face)
      (ecb-source-in-directories-buffer-face . ecb-source-in-directories-buffer-face)
      (ecb-source-read-only-face . ecb-source-read-only-face)
      (ecb-sources-general-face . ecb-default-general-face)
      (ecb-tag-header-face . ecb-tag-header-face)
      (ecb-tree-guide-line-face . ecb-tree-guide-line-face)
      (highline-face . dmb-current-line-face)
      (highline-vertical-face . highline-vertical-face)
      (ibuffer-deletion-face . font-lock-type-face)
      (ibuffer-filter-group-name-face . bold)
      (ibuffer-marked-face . font-lock-warning-face)
      (ibuffer-title-face . font-lock-type-face)
      (list-matching-lines-buffer-name-face . underline)
      (list-matching-lines-face . match)
      (moccur-maximum-displayed-with-color . 500)
      (paren-match-face . paren-face-match)
      (paren-mismatch-face . paren-face-mismatch)
      (paren-no-match-face . paren-face-no-match)
      (ps-line-number-color . "black")
      (ps-zebra-color . 0.95)
      (rmail-highlight-face . rmail-highlight)
      (tags-tag-face . default)
      (vc-annotate-very-old-color . "#3F3FFF")
      (view-highlight-face . highlight)
      (viper-insert-state-cursor-color . "Green")
      (viper-replace-overlay-cursor-color . "Red")
      (widget-mouse-face . highlight))
     (default ((t (:bold t :stipple nil :background "black" :foreground "grey75" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight bold :height 83 :width normal :family "outline-consolas"))))
     (ansi-color-names-vector ((t (nil))))
     (anything-header ((t (:width normal :box (:line-width -1 :color "SteelBlue4") :background "grey90" :foreground "grey20" :box nil))))
     (anything-isearch-match ((t (:background "Yellow"))))
     (blue ((t (:foreground "blue"))))
     (bold ((t (:bold t :weight bold))))
     (bold-italic ((t (:bold t :weight bold))))
     (border ((t (:background "black"))))
     (border-glyph ((t (nil))))
     (buffer-menu-buffer ((t (:bold t :weight bold))))
     (buffers-tab ((t (:background "black" :foreground "white"))))
     (button ((t (:underline t))))
     (c-nonbreakable-space-face ((t (:bold t :background "Red1" :weight bold))))
     (calendar-today-face ((t (:underline t))))
     (change-log-acknowledgement ((t (:foreground "grey67"))))
     (change-log-conditionals ((t (:foreground "darkseagreen"))))
     (change-log-date ((t (:foreground "PaleTurquoise4"))))
     (change-log-email ((t (:foreground "darkseagreen"))))
     (change-log-file ((t (:foreground "LightSteelBlue"))))
     (change-log-function ((t (:foreground "darkseagreen"))))
     (change-log-list ((t (:foreground "aquamarine3"))))
     (change-log-name ((t (:foreground "SlateGray3"))))
     (comint-highlight-input ((t (:foreground "DarkSeaGreen"))))
     ;;(comint-highlight-prompt ((t (:foreground "LightSkyBlue"))))
     (comint-highlight-prompt ((t (:foreground "#357797"))))
     (compilation-column-number ((t (:foreground "LightSlateGray"))))
     (compilation-error ((t (:bold t :weight bold :foreground "RosyBrown"))))
     (compilation-info ((t (:foreground "LightSkyBlue"))))
     (compilation-line-number ((t (:foreground "darkseagreen" :underline nil))))
     (compilation-warning ((t (:bold t :foreground "Orange" :weight bold))))
     (completions-common-part ((t (:bold t :family "outline-consolas" :width normal :weight bold :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "grey75" :background "black" :stipple nil :height 83))))
     (completions-first-difference ((t (:foreground "pale goldenrod"))))
     (cperl-array-face ((t (:foreground "darkseagreen"))))
     (cperl-hash-face ((t (:foreground "darkseagreen"))))
     (cperl-nonoverridable-face ((t (:foreground "SkyBlue"))))
     (cursor ((t (:background "yellow" :foreground "white"))))
     (custom-button ((t (nil))))
     (custom-button-mouse ((t (:background "grey90" :foreground "black" :box (:line-width 2 :style released-button)))))
     (custom-button-pressed ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style pressed-button)))))
     (custom-button-pressed-unraised ((t (:underline nil :foreground "magenta4"))))
     (custom-button-unraised ((t (:underline nil))))
     (custom-changed ((t (:background "blue" :foreground "white"))))
     (custom-comment ((t (:background "gray85"))))
     (custom-comment-tag ((t (:foreground "blue4"))))
     (custom-documentation ((t (nil))))
     (custom-face-tag ((t (:underline t))))
     (custom-group-tag ((t (:foreground "light blue" :underline t))))
     (custom-group-tag-1 ((t (:foreground "pink" :underline t))))
     (custom-invalid ((t (:background "red" :foreground "yellow"))))
     (custom-link ((t (:underline t :foreground "blue1"))))
     (custom-modified ((t (:background "blue" :foreground "white"))))
     (custom-rogue ((t (:background "black" :foreground "pink"))))
     (custom-saved ((t (:underline t))))
     (custom-set ((t (:background "white" :foreground "blue"))))
     (custom-state ((t (:foreground "lime green"))))
     (custom-themed ((t (:background "blue1" :foreground "white"))))
     (custom-variable-button ((t (:bold t :underline t :weight bold))))
     (custom-variable-tag ((t (:foreground "light blue" :underline t))))
     (custom-visibility ((t (:underline t :foreground "blue1" :height 0.8))))
     (diary-face ((t (:foreground "IndianRed"))))
     (diff-added ((t (nil))))
     (diff-changed ((t (nil))))
     (diff-context ((t (:foreground "grey50"))))
     (diff-file-header ((t (:bold t :background "grey70" :weight bold))))
     (diff-function ((t (:background "grey85"))))
     (diff-header ((t (:background "grey85"))))
     (diff-hunk-header ((t (:background "grey85"))))
     (diff-index ((t (:bold t :weight bold :background "grey70"))))
     (diff-indicator-added ((t (nil))))
     (diff-indicator-changed ((t (nil))))
     (diff-indicator-removed ((t (nil))))
     (diff-nonexistent ((t (:bold t :weight bold :background "grey70"))))
     (diff-refine-change ((t (:background "grey90"))))
     (diff-removed ((t (nil))))
     (dired-directory ((t (:foreground "LightSkyBlue"))))
     (dired-flagged ((t (:foreground "RosyBrown3"))))
     (dired-header ((t (:foreground "LightGoldenrod"))))
     (dired-ignored ((t (:foreground "grey51"))))
     (dired-mark ((t (:foreground "SlateGray3"))))
     (dired-marked ((t (:foreground "IndianRed"))))
     (dired-symlink ((t (:foreground "aquamarine3"))))
     (dired-warn-writable ((t (:bold t :family "outline-consolas" :width normal :weight bold :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "grey75" :background "black" :stipple nil :height 83))))
     (dired-warning ((t (:bold t :weight bold :foreground "RosyBrown"))))
     (dmb-blink-region-face ((t (:background "lavendar"))))
     (dmb-current-line-face ((t (:background "#2C932CDA4101"))))
     (dmb-face-five ((t (:foreground "IndianRed"))))
     (dmb-face-four ((t (:foreground "#997009"))))
     (dmb-face-hi-light-line-error ((t (:foreground "maroon"))))
     (dmb-face-ibuffer-elisp ((t (:foreground "SeaGreen"))))
     (dmb-face-ibuffer-jde ((t (:foreground "LightSlateGray"))))
     (dmb-face-light-blue ((t (:foreground "LightSkyBlue"))))
     (dmb-face-one ((t (:foreground "midnight blue"))))
     (dmb-face-onex ((t (:foreground "LightSkyBlue"))))
     (dmb-face-six ((t (:foreground "DarkSlateBlue"))))
     (dmb-face-three ((t (:foreground "DarkSeaGreen"))))
     (dmb-face-two ((t (:foreground "medium sea green"))))
     (dmb-grep-hit-face ((t (:foreground "LightSlateGray"))))
     (dmb-grep-match-face ((t (:foreground "DarkSlateBlue" :underline nil))))
     (dmb-mark-face ((t (:foreground "cyan" :underline nil))))
     (dmb-notes-txt-face ((t (:foreground "DodgerBlue" :underline nil))))
     (ecb-bucket-node-face ((t (:bold t :weight bold :height 1.0))))
     (ecb-default-general-face ((t (:height 1.0))))
     (ecb-default-highlight-face ((t (:background "cornflower blue" :foreground "yellow"))))
     (ecb-directories-general-face ((t (:height 1.0))))
     (ecb-directory-face ((t (:background "cornflower blue" :foreground "yellow"))))
     (ecb-directory-not-accessible-face ((t (:foreground "gray60" :height 1.0))))
     (ecb-history-face ((t (:background "cornflower blue" :foreground "yellow"))))
     (ecb-history-general-face ((t (:height 1.0))))
     (ecb-method-face ((t (:background "cornflower blue" :foreground "yellow"))))
     (ecb-method-non-semantic-face ((t (:foreground "brown" :height 1.0))))
     (ecb-methods-general-face ((t (:height 1.0))))
     (ecb-mode-line-data-face ((t (nil))))
     (ecb-mode-line-prefix-face ((t (:foreground "forestgreen"))))
     (ecb-mode-line-win-nr-face ((t (:bold t :weight bold))))
     (ecb-source-face ((t (:background "cornflower blue" :foreground "yellow"))))
     (ecb-source-in-directories-buffer-face ((t (:foreground "medium blue" :height 1.0))))
     (ecb-source-read-only-face ((t (:italic t :slant italic))))
     (ecb-sources-general-face ((t (:height 1.0))))
     (ecb-tag-header-face ((t (:background "SeaGreen1"))))
     (ecb-tree-guide-line-face ((t (:foreground "grey" :height 1.0))))
     (ecb-type-tag-class-face ((t (:bold t :weight bold))))
     (ecb-type-tag-enum-face ((t (:bold t :weight bold))))
     (ecb-type-tag-group-face ((t (:bold t :foreground "dim gray" :weight bold))))
     (ecb-type-tag-interface-face ((t (:bold t :weight bold))))
     (ecb-type-tag-struct-face ((t (:bold t :weight bold))))
     (ecb-type-tag-typedef-face ((t (:bold t :weight bold))))
     (ecb-type-tag-union-face ((t (:bold t :weight bold))))
     (ediff-current-diff-A ((t (:background "#b38080" :foreground "grey"))))
     (ediff-current-diff-Ancestor ((t (:background "VioletRed" :foreground "Black"))))
     (ediff-current-diff-B ((t (:background "#2c6a8f" :foreground "grey"))))
     (ediff-current-diff-C ((t (:background "Pink" :foreground "Navy"))))
     (ediff-even-diff-A ((t (:foreground "grey51"))))
     (ediff-even-diff-Ancestor ((t (:background "Grey" :foreground "White"))))
     (ediff-even-diff-B ((t (:foreground "grey51"))))
     (ediff-even-diff-C ((t (:background "light grey" :foreground "Black"))))
     (ediff-fine-diff-A ((t (:background "pale goldenrod" :foreground "black"))))
     (ediff-fine-diff-Ancestor ((t (:background "Green" :foreground "Black"))))
     (ediff-fine-diff-B ((t (:background "pale goldenrod" :foreground "black"))))
     (ediff-fine-diff-C ((t (:background "Turquoise" :foreground "Black"))))
     (ediff-odd-diff-A ((t (:background "grey26"))))
     (ediff-odd-diff-Ancestor ((t (:background "gray40" :foreground "cyan3"))))
     (ediff-odd-diff-B ((t (:background "grey26"))))
     (ediff-odd-diff-C ((t (:background "Grey" :foreground "White"))))
     (eieio-custom-slot-tag-face ((t (:foreground "blue"))))
     (eldoc-highlight-function-argument ((t (:bold t :weight bold))))
     (erc-action-face ((t (:bold t :weight bold))))
     (erc-bold-face ((t (:bold t :weight bold))))
     (erc-default-face ((t (nil))))
     (erc-direct-msg-face ((t (:foreground "sandybrown"))))
     (erc-error-face ((t (:bold t :foreground "IndianRed" :weight bold))))
     (erc-input-face ((t (:foreground "Beige"))))
     (erc-inverse-face ((t (:background "wheat" :foreground "darkslategrey"))))
     (erc-notice-face ((t (:foreground "MediumAquamarine"))))
     (erc-pal-face ((t (:foreground "pale green"))))
     (erc-prompt-face ((t (:foreground "MediumAquamarine"))))
     (erc-underline-face ((t (:underline t))))
     (escape-glyph ((t (:foreground "brown"))))
     (eshell-ls-archive-face ((t (:bold t :foreground "IndianRed" :weight bold))))
     (eshell-ls-backup-face ((t (:foreground "Grey"))))
     (eshell-ls-clutter-face ((t (:foreground "DimGray"))))
     (eshell-ls-directory-face ((t (:bold t :foreground "MediumSlateBlue" :weight bold))))
     (eshell-ls-executable-face ((t (:foreground "Coral"))))
     (eshell-ls-missing-face ((t (:foreground "black"))))
     (eshell-ls-picture-face ((t (:foreground "Violet"))))
     (eshell-ls-product-face ((t (:foreground "sandybrown"))))
     (eshell-ls-readonly-face ((t (:foreground "Aquamarine"))))
     (eshell-ls-special-face ((t (:foreground "Gold"))))
     (eshell-ls-symlink-face ((t (:foreground "White"))))
     (eshell-ls-unreadable-face ((t (:foreground "DimGray"))))
     (eshell-prompt-face ((t (:foreground "MediumAquamarine"))))
     (ffap ((t (:background "darkolivegreen"))))
     (file-name-shadow ((t (:foreground "LightSlateGray"))))
     (fixed-pitch ((t (:family "courier"))))
     (fl-comment-face ((t (:foreground "pink"))))
     (fl-doc-string-face ((t (:foreground "purple"))))
     (fl-function-name-face ((t (:foreground "red"))))
     (fl-keyword-face ((t (:foreground "cadetblue"))))
     (fl-string-face ((t (:foreground "green"))))
     (fl-type-face ((t (:foreground "yellow"))))
     (flymake-errline ((t (:underline "OrangeRed"))))
     (flymake-warnline ((t (:underline "DarkSlateBlue"))))
     (font-lock-builtin-face ((t (:foreground "LightSteelBlue"))))
     (font-lock-comment-delimiter-face ((t (:bold t :foreground "grey67" :weight bold))))
     (font-lock-comment-face ((t (:foreground "grey67"))))
     (font-lock-constant-face ((t (:foreground "SlateGray3"))))
     (font-lock-doc-face ((t (:foreground "grey67"))))
     (font-lock-function-name-face ((t (:foreground "LightSteelBlue"))))
     (font-lock-keyword-face ((t (:foreground "aquamarine3"))))
     (font-lock-negation-char-face ((t (nil))))
     (font-lock-preprocessor-face ((t (:foreground "Aquamarine"))))
     (font-lock-reference-face ((t (:foreground "SlateBlue"))))
     (font-lock-regexp-grouping-backslash ((t (:bold t :weight bold))))
     (font-lock-regexp-grouping-construct ((t (:bold t :weight bold))))
     (font-lock-string-face ((t (:foreground "PaleTurquoise4"))))
     (font-lock-type-face ((t (:foreground "LightSlateGray"))))
     (font-lock-variable-name-face ((t (:foreground "darkseagreen"))))
     (font-lock-warning-face ((t (:bold t :foreground "RosyBrown" :weight bold))))
     (fringe ((t (:background "black"))))
     (gnus-cite-attribution-face ((t (nil))))
     (gnus-cite-face-1 ((t (:bold t :foreground "deep sky blue" :weight bold))))
     (gnus-cite-face-10 ((t (:foreground "medium purple"))))
     (gnus-cite-face-11 ((t (:foreground "turquoise"))))
     (gnus-cite-face-2 ((t (:bold t :foreground "cadetblue" :weight bold))))
     (gnus-cite-face-3 ((t (:bold t :foreground "gold" :weight bold))))
     (gnus-cite-face-4 ((t (:foreground "light pink"))))
     (gnus-cite-face-5 ((t (:foreground "pale green"))))
     (gnus-cite-face-6 ((t (:bold t :foreground "chocolate" :weight bold))))
     (gnus-cite-face-7 ((t (:foreground "orange"))))
     (gnus-cite-face-8 ((t (:foreground "magenta"))))
     (gnus-cite-face-9 ((t (:foreground "violet"))))
     (gnus-emphasis-bold ((t (:bold t :weight bold))))
     (gnus-emphasis-bold-italic ((t (:bold t :weight bold))))
     (gnus-emphasis-highlight-words ((t (:background "black" :foreground "yellow"))))
     (gnus-emphasis-italic ((t (nil))))
     (gnus-emphasis-underline ((t (:underline t))))
     (gnus-emphasis-underline-bold ((t (:bold t :underline t :weight bold))))
     (gnus-emphasis-underline-bold-italic ((t (:bold t :underline t :weight bold))))
     (gnus-emphasis-underline-italic ((t (:underline t))))
     (gnus-group-mail-1-empty-face ((t (:foreground "aquamarine1"))))
     (gnus-group-mail-1-face ((t (:bold t :foreground "aquamarine1" :weight bold))))
     (gnus-group-mail-2-empty-face ((t (:foreground "aquamarine2"))))
     (gnus-group-mail-2-face ((t (:bold t :foreground "aquamarine2" :weight bold))))
     (gnus-group-mail-3-empty-face ((t (:foreground "aquamarine3"))))
     (gnus-group-mail-3-face ((t (:bold t :foreground "aquamarine3" :weight bold))))
     (gnus-group-mail-low-empty-face ((t (:foreground "aquamarine4"))))
     (gnus-group-mail-low-face ((t (:bold t :foreground "aquamarine4" :weight bold))))
     (gnus-group-news-1-empty-face ((t (:foreground "PaleTurquoise"))))
     (gnus-group-news-1-face ((t (:bold t :foreground "PaleTurquoise" :weight bold))))
     (gnus-group-news-2-empty-face ((t (:foreground "turquoise"))))
     (gnus-group-news-2-face ((t (:bold t :foreground "turquoise" :weight bold))))
     (gnus-group-news-3-empty-face ((t (nil))))
     (gnus-group-news-3-face ((t (:bold t :weight bold))))
     (gnus-group-news-4-empty-face ((t (nil))))
     (gnus-group-news-4-face ((t (:bold t :weight bold))))
     (gnus-group-news-5-empty-face ((t (nil))))
     (gnus-group-news-5-face ((t (:bold t :weight bold))))
     (gnus-group-news-6-empty-face ((t (nil))))
     (gnus-group-news-6-face ((t (:bold t :weight bold))))
     (gnus-group-news-low-empty-face ((t (:foreground "DarkTurquoise"))))
     (gnus-group-news-low-face ((t (:bold t :foreground "DarkTurquoise" :weight bold))))
     (gnus-header-content-face ((t (:foreground "forest green"))))
     (gnus-header-from-face ((t (:bold t :foreground "spring green" :weight bold))))
     (gnus-header-name-face ((t (:foreground "deep sky blue"))))
     (gnus-header-newsgroups-face ((t (:bold t :foreground "purple" :weight bold))))
     (gnus-header-subject-face ((t (:bold t :foreground "orange" :weight bold))))
     (gnus-signature-face ((t (:bold t :foreground "khaki" :weight bold))))
     (gnus-splash-face ((t (:foreground "Brown"))))
     (gnus-summary-cancelled-face ((t (:background "black" :foreground "yellow"))))
     (gnus-summary-high-ancient-face ((t (:bold t :foreground "SkyBlue" :weight bold))))
     (gnus-summary-high-read-face ((t (:bold t :foreground "PaleGreen" :weight bold))))
     (gnus-summary-high-ticked-face ((t (:bold t :foreground "pink" :weight bold))))
     (gnus-summary-high-unread-face ((t (:bold t :weight bold))))
     (gnus-summary-low-ancient-face ((t (:foreground "SkyBlue"))))
     (gnus-summary-low-read-face ((t (:foreground "PaleGreen"))))
     (gnus-summary-low-ticked-face ((t (:foreground "pink"))))
     (gnus-summary-low-unread-face ((t (nil))))
     (gnus-summary-normal-ancient-face ((t (:foreground "SkyBlue"))))
     (gnus-summary-normal-read-face ((t (:foreground "PaleGreen"))))
     (gnus-summary-normal-ticked-face ((t (:foreground "pink"))))
     (gnus-summary-normal-unread-face ((t (nil))))
     (gnus-summary-selected-face ((t (:underline t))))
     (green ((t (:foreground "green"))))
     (gui-button-face ((t (:background "grey75" :foreground "black"))))
     (gui-element ((t (:background "#D4D0C8" :foreground "black"))))
     (header-line ((t (:width normal :box (:line-width -1 :color "SteelBlue4") :background "grey90" :foreground "grey20" :box nil))))
     (help-argument-name ((t (nil))))
     (hi-black-b ((t (:bold t :weight bold))))
     (hi-black-hb ((t (:bold t :family "helv" :weight bold :height 1.67))))
     (hi-blue ((t (:background "light blue"))))
     (hi-blue-b ((t (:bold t :foreground "blue1" :weight bold))))
     (hi-green ((t (:foreground "PaleGreen2"))))
     (hi-green-b ((t (:bold t :foreground "green1" :weight bold))))
     (hi-indian-red ((t (:background "IndianRed1"))))
     (hi-indian-red-fg ((t (:foreground "IndianRed1"))))
     (hi-lemon-chiffon ((t (:background "lemon chiffon"))))
     (hi-light-goldenrod ((t (:background "light goldenrod"))))
     (hi-pink ((t (:background "pink"))))
     (hi-red-b ((t (:bold t :foreground "red1" :weight bold))))
     (hi-yellow ((t (:background "yellow1"))))
     (highlight ((t (:background "darkolivegreen"))))
     (highline-face ((t (:background "SeaGreen"))))
     (highline-vertical-face ((t (:background "darkslateblue"))))
     (holiday-face ((t (:background "DimGray"))))
     (ido-first-match ((t (:bold t :weight bold))))
     (ido-incomplete-regexp ((t (:bold t :weight bold :foreground "RosyBrown"))))
     (ido-indicator ((t (:background "red1" :foreground "yellow1" :width condensed))))
     (ido-only-match ((t (:foreground "ForestGreen"))))
     (ido-subdir ((t (:foreground "red1"))))
     (info-header-node ((t (:bold t :weight bold :underline t :foreground "DodgerBlue1"))))
     (info-header-xref ((t (:underline t :foreground "LightSlateGray"))))
     (info-menu-header ((t (:bold t :family "helv" :weight bold))))
     (info-menu-star ((t (:underline t))))
     (info-node ((t (:bold t :foreground "DodgerBlue1" :underline t :weight bold))))
     (info-title-1 ((t (:bold t :weight bold :family "helv" :height 1.728))))
     (info-title-2 ((t (:bold t :family "helv" :weight bold :height 1.44))))
     (info-title-3 ((t (:bold t :weight bold :family "helv" :height 1.2))))
     (info-title-4 ((t (:bold t :family "helv" :weight bold))))
     (info-xref ((t (:foreground "LightSlateGray" :underline t))))
     (info-xref-visited ((t (:foreground "magenta4" :underline t))))
     (isearch ((t (:background "blue"))))
     (isearch-secondary ((t (:background "DimGray" :foreground "red3"))))
     (iswitchb-current-match ((t (:foreground "LightSkyBlue"))))
     (iswitchb-invalid-regexp ((t (:bold t :weight bold :foreground "RosyBrown"))))
     (iswitchb-single-match ((t (:foreground "IndianRed"))))
     (iswitchb-virtual-matches ((t (:foreground "LightSteelBlue"))))
     (italic ((t (nil))))
     (jabber-activity-face ((t (:bold t :foreground "red" :weight bold))))
     (jabber-chat-error ((t (:bold t :foreground "red" :weight bold))))
     (jabber-chat-prompt-foreign ((t (:bold t :foreground "red" :weight bold))))
     (jabber-chat-prompt-local ((t (:bold t :foreground "blue" :weight bold))))
     (jabber-chat-prompt-system ((t (:bold t :foreground "green" :weight bold))))
     (jabber-chat-text-foreign ((t (nil))))
     (jabber-chat-text-local ((t (nil))))
     (jabber-rare-time-face ((t (:foreground "darkgreen" :underline t))))
     (jabber-roster-user-away ((t (:italic t :foreground "dark green" :slant italic :weight normal))))
     (jabber-roster-user-chatty ((t (:bold t :foreground "dark orange" :slant normal :weight bold))))
     (jabber-roster-user-dnd ((t (:italic t :foreground "red" :slant italic :weight normal))))
     (jabber-roster-user-error ((t (:italic t :foreground "red" :slant italic :weight light))))
     (jabber-roster-user-offline ((t (:italic t :foreground "dark grey" :slant italic :weight light))))
     (jabber-roster-user-online ((t (:bold t :foreground "blue" :slant normal :weight bold))))
     (jabber-roster-user-xa ((t (:italic t :foreground "black" :slant italic :weight normal))))
     (jabber-title-large ((t (:bold t :family "helv" :weight bold :height 3.0 :width ultra-expanded))))
     (jabber-title-medium ((t (:bold t :family "helv" :weight bold :height 2.0 :width expanded))))
     (jabber-title-small ((t (:bold t :family "helv" :weight bold :height 1.0 :width semi-expanded))))
     (jde-bug-breakpoint-cursor ((t (:background "brown" :foreground "cyan"))))
     (jde-db-active-breakpoint-face ((t (:background "red" :foreground "black"))))
     (jde-db-requested-breakpoint-face ((t (:background "yellow" :foreground "black"))))
     (jde-db-spec-breakpoint-face ((t (:background "green" :foreground "black"))))
     (jde-java-font-lock-api-face ((t (:foreground "dark goldenrod"))))
     (jde-java-font-lock-bold-face ((t (:bold t :weight bold))))
     (jde-java-font-lock-code-face ((t (nil))))
     (jde-java-font-lock-constant-face ((t (:foreground "SlateGray3"))))
     (jde-java-font-lock-doc-tag-face ((t (:foreground "DarkSeaGreen"))))
     (jde-java-font-lock-italic-face ((t (:italic t :slant italic))))
     (jde-java-font-lock-link-face ((t (:foreground "bisque"))))
     (jde-java-font-lock-modifier-face ((t (:foreground "MediumTurquoise"))))
     (jde-java-font-lock-number-face ((t (:foreground "RosyBrown"))))
     (jde-java-font-lock-operator-face ((t (:foreground "medium blue"))))
     (jde-java-font-lock-package-face ((t (:foreground "blue3"))))
     (jde-java-font-lock-pre-face ((t (nil))))
     (jde-java-font-lock-private-face ((t (:foreground "Orchid"))))
     (jde-java-font-lock-protected-face ((t (:foreground "Orchid"))))
     (jde-java-font-lock-public-face ((t (:foreground "Orchid"))))
     (jde-java-font-lock-underline-face ((t (:underline t))))
     (lazy-highlight ((t (:background "paleturquoise"))))
     (left-margin ((t (nil))))
     (link ((t (:foreground "blue1" :underline t))))
     (link-visited ((t (:underline t :foreground "magenta4"))))
     (list-mode-item-selected ((t (:background "gray68" :foreground "white"))))
     (match ((t (:background "yellow1"))))
     (menu ((t (:foreground "systemmenu" :background "systemmenutext"))))
     (message-cited-text-face ((t (:bold t :foreground "green" :weight bold))))
     (message-header-cc-face ((t (:bold t :foreground "green4" :weight bold))))
     (message-header-name-face ((t (:bold t :foreground "orange" :weight bold))))
     (message-header-newsgroups-face ((t (:bold t :foreground "violet" :weight bold))))
     (message-header-other-face ((t (:bold t :foreground "chocolate" :weight bold))))
     (message-header-subject-face ((t (:bold t :foreground "yellow" :weight bold))))
     (message-header-to-face ((t (:bold t :foreground "cadetblue" :weight bold))))
     (message-header-xheader-face ((t (:bold t :foreground "light blue" :weight bold))))
     (message-mml-face ((t (:bold t :foreground "Green3" :weight bold))))
     (message-separator-face ((t (:foreground "blue3"))))
     (minibuffer-prompt ((t (:foreground "LightSkyBlue"))))
     (moccur-current-line-face ((t (:underline t))))
     (moccur-face ((t (:bold t :background "light cyan" :weight bold))))
     ;;(mode-line ((t (:background "gray20" :foreground "grey74" :box (:line-width -1 :color "SteelBlue4") :width normal))))
     
     ;;(mode-line ((t (:background "WhiteSmoke" :foreground "black" :overline "LightGray"))))  ;;:background "GhostWhite" ;;:background "gray91"    
     (mode-line-buffer-id ((t (:foreground "grey74"))))
     (mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
     (mode-line ((t (:background "grey8" :foreground "grey74" :overline "grey36" ))))
     (mode-line-inactive ((t (:background "gray8" :foreground "grey50" :overline "SteelBlue4" ))))
     ;;(mode-line-inactive ((t (:background "gray20" :foreground "grey50" :box (:line-width -1 :color "SteelBlue4") :width normal ))))
     (modeline-mousable ((t (:background "DarkRed" :foreground "white"))))
     (modeline-mousable-minor-mode ((t (:background "DarkRed" :foreground "white"))))
     (mouse ((t (:background "sienna1"))))
     (next-error ((t (:foreground "CadetBlue3" :background "blue4"))))
     (nobreak-space ((t (:foreground "brown" :underline t))))
     (outline-1 ((t (:foreground "SkyBlue"))))
     (outline-2 ((t (:foreground "darkseagreen"))))
     (outline-3 ((t (:foreground "aquamarine3"))))
     (outline-4 ((t (:foreground "grey67"))))
     (outline-5 ((t (:foreground "LightSlateGray"))))
     (outline-6 ((t (:foreground "SlateGray3"))))
     (outline-7 ((t (:foreground "LightSteelBlue"))))
     (outline-8 ((t (:foreground "PaleTurquoise4"))))
     (p4-depot-added-face ((t (:foreground "blue"))))
     (p4-depot-deleted-face ((t (:foreground "red"))))
     (p4-depot-unmapped-face ((t (:foreground "grey30"))))
     (p4-diff-change-face ((t (:foreground "dark green"))))
     (p4-diff-del-face ((t (:foreground "red"))))
     (p4-diff-file-face ((t (:background "gray90"))))
     (p4-diff-head-face ((t (:background "gray95"))))
     (p4-diff-ins-face ((t (:foreground "blue"))))
     (paren-face-match ((t (:background "turquoise" :foreground "black"))))
     (paren-face-mismatch ((t (:background "purple" :foreground "white"))))
     (paren-face-no-match ((t (:background "yellow" :foreground "black"))))
     (pointer ((t (nil))))
     (primary-selection ((t (:background "blue"))))
     (qt-classes-face ((t (:foreground "Red"))))
     (query-replace ((t (:background "blue"))))
     (red ((t (:foreground "red"))))
     (region ((t (:background "blue4" :foreground "CadetBlue3"))))
     (right-margin ((t (nil))))
     (scroll-bar ((t (:foreground "systemscrollbar"))))
     (search-buffers-face ((t (:bold t :background "ForestGreen" :weight bold))))
     (search-buffers-header-face ((t (:bold t :background "ForestGreen" :weight bold))))
     (secondary-selection ((t (:background "darkslateblue"))))
     (semantic-decoration-on-private-members-face ((t (:background "#8fffff"))))
     (semantic-decoration-on-protected-members-face ((t (:background "#fffff8"))))
     (semantic-highlight-edits-face ((t (:background "gray90"))))
     ;;(semantic-tag-boundary-face ((t (:overline "blue"))))
     (semantic-tag-boundary-face ((((class color)) (:slant italic))))
     (semantic-tag-highlight-face ((t (:background "#FFFFAA"))))
     (semantic-tag-highlight-start-face ((t (:background "#FFFFAA"))))
     (semantic-unmatched-syntax-face ((t (:underline "red"))))
     (senator-intangible-face ((t (:foreground "gray25"))))
     (senator-momentary-highlight-face ((t (:background "gray70"))))
     (senator-read-only-face ((t (:background "#CCBBBB"))))
     (sgml-namespace-face ((t (:foreground "LightSteelBlue"))))
     (shadow ((t (:foreground "grey50"))))
     (show-paren-match-face ((t (:background "DarkSeaGreen" :foreground "SlateBlue"))))
     (show-paren-mismatch-face ((t (:background "Red" :foreground "White"))))
     (sldb-catch-tag-face ((t (nil))))
     (sldb-condition-face ((t (nil))))
     (sldb-detailed-frame-line-face ((t (nil))))
     (sldb-frame-label-face ((t (nil))))
     (sldb-frame-line-face ((t (nil))))
     (sldb-local-name-face ((t (nil))))
     (sldb-local-value-face ((t (nil))))
     (sldb-reference-face ((t (:underline t))))
     (sldb-restart-face ((t (nil))))
     (sldb-restart-number-face ((t (:bold t :weight bold))))
     (sldb-restart-type-face ((t (:foreground "aquamarine3"))))
     (sldb-section-face ((t (nil))))
     (sldb-topline-face ((t (nil))))
     (slime-error-face ((t (:underline "red"))))
     (slime-highlight-edits-face ((t (:background "lightgray"))))
     (slime-highlight-face ((t (:background "darkolivegreen" :underline nil))))
     (slime-inspector-action-face ((t (:bold t :weight bold :foreground "RosyBrown"))))
     (slime-inspector-label-face ((t (:foreground "SlateGray3"))))
     (slime-inspector-topline-face ((t (nil))))
     (slime-inspector-type-face ((t (:foreground "LightSlateGray"))))
     (slime-inspector-value-face ((t (:foreground "LightSteelBlue"))))
     (slime-note-face ((t (:underline "brown4"))))
     (slime-reader-conditional-face ((t (:foreground "grey67"))))
     (slime-repl-input-face ((t (:bold t :weight bold))))
     (slime-repl-inputed-output-face ((t (:foreground "SkyBlue"))))
     (slime-repl-output-face ((t (:foreground "PaleTurquoise4"))))
     (slime-repl-output-mouseover-face ((t (:foreground "SkyBlue" :box (:line-width 1 :color "black" :style released-button)))))
     (slime-repl-prompt-face ((t (:foreground "aquamarine3"))))
     (slime-repl-result-face ((t (nil))))
     (slime-style-warning-face ((t (:underline "brown"))))
     (slime-warning-face ((t (:underline "orange"))))
     (speedbar-button-face ((t (:foreground "green4"))))
     (speedbar-directory-face ((t (:foreground "blue4"))))
     (speedbar-file-face ((t (:foreground "cyan4"))))
     (speedbar-highlight-face ((t (:background "green"))))
     (speedbar-selected-face ((t (:foreground "red" :underline t))))
     (speedbar-separator-face ((t (:background "blue" :foreground "white" :overline "gray"))))
     (speedbar-tag-face ((t (:foreground "brown"))))
     (svn-status-directory-face ((t (:foreground "blue4"))))
     (svn-status-filename-face ((t (:foreground "chocolate"))))
     (svn-status-locked-face ((t (:bold t :foreground "Red" :weight bold))))
     (svn-status-marked-face ((t (:foreground "green3"))))
     (svn-status-marked-popup-face ((t (:foreground "green3"))))
     (svn-status-switched-face ((t (:foreground "CadetBlue"))))
     (svn-status-symlink-face ((t (:foreground "cornflower blue"))))
     (svn-status-update-available-face ((t (:foreground "magenta"))))
     (tempo-x-auto-face ((t (:background "light gray"))))
     (tempo-x-editable-face ((t (:background "light cyan"))))
     (tempo-x-form-face ((t (:background "light gray"))))
     (tool-bar ((t (nil))))
     (tooltip ((t (:family "helv" :background "systeminfowindow" :foreground "systeminfotext"))))
     (trailing-whitespace ((t (:background "red1"))))
     (underline ((t (:underline nil))))
     (variable-pitch ((t (:family "helv"))))
     (vertical-border ((t (nil))))
     (vertical-divider ((t (nil))))
     (viper-minibuffer-emacs ((t (:background "darkseagreen2" :foreground "Black"))))
     (viper-minibuffer-insert ((t (:background "pink" :foreground "Black"))))
     (viper-minibuffer-vi ((t (:background "grey" :foreground "DarkGreen"))))
     (viper-replace-overlay ((t (:background "darkseagreen2" :foreground "Black"))))
     (viper-search ((t (:background "khaki" :foreground "Black"))))
     (which-func ((t (:foreground "LightSteelBlue"))))
     (widget ((t (nil))))
     (widget-button ((t (:bold t :weight bold))))
     (widget-button-pressed ((t (:foreground "red"))))
     (widget-documentation ((t (:foreground "lime green"))))
     (widget-field ((t (:background "dim gray"))))
     (widget-inactive ((t (:foreground "light gray"))))
     (widget-single-line-field ((t (:background "dim gray"))))
     (woman-addition-face ((t (:foreground "orange"))))
     (woman-bold-face ((t (:bold t :weight bold))))
     (woman-italic-face ((t (:foreground "beige"))))
     (woman-symbol-face ((t (nil))))
     (woman-unknown-face ((t (:foreground "LightSalmon"))))
     (yellow ((t (:foreground "yellow"))))
     (buffer-menu-buffer-name ((t (:foreground "grey"))))
     (buffer-menu-star-buffer ((t (:foreground "PaleTurquoise4"))))
     (buffer-menu-directory-buffer ((t (:foreground "MediumTurquoise" ))))
     (buffer-menu-delete-mark ((t (:foreground "red4" ))))
     (buffer-menu-file-name ((t (:foreground "PaleTurquoise4" ))))
     (buffer-menu-mode ((t (:foreground "AntiqueWhite4" ))))
     (buffer-menu-time ((t (:foreground "PaleTurquoise4" ))))
     (buffer-menu-size ((t (:foreground "DarkSlateGrey" ))))
     (buffer-menu-flagged-buffer ((t (:foreground "red4" ))))
     (buffer-menu-read-only-mark ((t (:foreground "chocolate1" ))))
     (zmacs-region ((t (:background "snow" :foreground "blue"))))))

  (custom-set-variables
   '(ansi-color-names-vector (vector "gray" "sienna" "light gray" "yellow" "SeaGreen" "magenta" "cyan" "white"))
   ))

(add-to-list 'color-themes '(color-theme--dmb-arjen2 \"Dave Boon dark \" \"dmb\"))




