(custom-set-variables
 '(font-menu-this-frame-only-p t)
 '(jde-auto-parse-enable nil)
 '(display-time-day-and-date t)
 '(jde-project-file-name "daveprj.el")
 '(truncate-lines t)
 '(get-frame-for-buffer-default-instance-limigt nil)
 '(display-time-show-icons-maybe nil)
 '(jde-compile-option-sourcepath (quote ("d:\\pakss_dev\\server\\src")))
 '(toolbar-visible-p nil)
 '(jde-compile-option-directory "d:\\pakss_dev\\server\\WEB-INF\\classes")
 '(jde-make-program "")
 '(blink-cursor-mode 0.6)
 '(shell-multiple-shells t)
 '(paren-mode (quote paren) nil (paren))
 '(query-user-mail-address nil)
 '(pc-select-selection-keys-only t)
 '(split-height-threshold 100)
 '(column-number-mode t)
 '(indent-tabs-mode nil)
 '(visible-bell nil)
 '(scrollbars-visible-p t)
 '(user-mail-address "david_boon@xelus.com")
 '(baud-rate 56000)
 '(delete-selection-mode t nil (delsel))
 '(pc-selection-mode nil nil (pc-select))
 '(hscroll-global-mode t nil (hscroll))
 '(delete-key-deletes-forward t))
